flat_growth.Rmd:
  path: dev/flat_growth.Rmd
  state: active
  R: R/gro_rout_quan.R
  tests: tests/testthat/test-gro_rout_quan.R
  vignettes: vignettes/growth.Rmd
  inflate:
    flat_file: dev/flat_growth.Rmd
    vignette_name: Growth
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_repro.Rmd:
  path: dev/flat_repro.Rmd
  state: active
  R:
  - R/rep_agemat.R
  - R/rep_birthinterval.R
  - R/rep_fert.R
  - R/rep_littersize.R
  - R/rep_lrs.R
  - R/rep_main.R
  - R/rep_pattern.R
  - R/rep_prepdata.R
  - R/rep_season.R
  - R/rep_weight1strepro.R
  tests:
  - tests/testthat/test-rep_main.R
  - tests/testthat/test-rep_agemat.R
  - tests/testthat/test-rep_littersize.R
  - tests/testthat/test-rep_birthinterval.R
  - tests/testthat/test-rep_fert.R
  - tests/testthat/test-rep_season.R
  - tests/testthat/test-rep_pattern.R
  - tests/testthat/test-rep_weight1strepro.R
  - tests/testthat/test-rep_lrs.R
  - tests/testthat/test-rep_prepdata.R
  vignettes: vignettes/reproduction.Rmd
  inflate:
    flat_file: dev/flat_repro.Rmd
    vignette_name: Reproduction
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_survival.Rmd:
  path: dev/flat_survival.Rmd
  state: active
  R:
  - R/find_gaps.R
  - R/km_age.R
  - R/km_lx.R
  - R/select_longthreshold.R
  - R/sur_age.R
  - R/sur_ana.R
  - R/sur_lx.R
  - R/sur_main.R
  - R/sur_out.R
  - R/sur_ple.R
  - R/sur_relex.R
  - R/sur_xx.R
  - R/surv_bastab.R
  tests:
  - tests/testthat/test-sur_main.R
  - tests/testthat/test-sur_ana.R
  - tests/testthat/test-sur_out.R
  - tests/testthat/test-surv_bastab.R
  - tests/testthat/test-sur_ple.R
  - tests/testthat/test-sur_relex.R
  - tests/testthat/test-sur_age.R
  - tests/testthat/test-sur_xx.R
  - tests/testthat/test-km_age.R
  - tests/testthat/test-km_lx.R
  - tests/testthat/test-select_longthreshold.R
  - tests/testthat/test-find_gaps.R
  vignettes: vignettes/survival.Rmd
  inflate:
    flat_file: dev/flat_survival.Rmd
    vignette_name: Survival
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
