# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_prepdata returns the correct structure", {
data(toy_core)
data(toy_collection)
data(toy_parent)

  Data <- Rep_prepdata(toy_core, offspring = toy_core, toy_collection, toy_parent,
                       MinNRepro = 1, MinNPaRepro = 1,
                       BirthType_parent = "Captive", 
                       BirthType_offspring = "Captive")
  
  expect_named(Data, c("Adults", "ReproData", "summary"))
  
  expect_named(Data$summary, c("Nbirths", "Nadults", "NPar_core", "NPar_off_core",
                               "NOffsp", "NParent", "NOffsp_age", "NParent_age", 
                               "NInst", "analyzed", "Nerr", "err"))
  
  expect_type(Data$Adults, "list")
  expect_s3_class(Data$Adults, "data.frame")
  expect_type(Data$ReproData, "list")
  expect_s3_class(Data$ReproData, "data.frame")
  
  expect_true(all(c("Age", "Date_age") %in% colnames(Data$Adults)))
  expect_true(all(c("ParentAge", "Probability") %in% colnames(Data$ReproData)))
})

test_that("Rep_prepdata flags insufficient parent records", {
  data(toy_core)
  data(toy_collection)
  data(toy_parent)

  
  result <- Rep_prepdata(toy_core, offspring = toy_core, toy_collection, toy_parent,
                         MinNPaRepro = 1000, MinNRepro = 1) # Force failure
  
  expect_false(result$summary$analyzed)
  expect_equal(result$summary$Nerr, 2)
  expect_match(result$summary$err, "Nparents < minNparep")
})

test_that("Rep_prepdata flags insufficient birth records", {
data(toy_core)
data(toy_collection)
data(toy_parent)


  result <- Rep_prepdata(toy_core, offspring = toy_core, toy_collection, toy_parent,
                         MinNRepro = 1000) # Force failure
  
  expect_false(result$summary$analyzed)
  expect_equal(result$summary$Nerr, 1)
  expect_match(result$summary$err, "Nbirths < MinNRepro")
})
