# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("surv_Bastab works", {
  data(core)
  data(deathinformation)
  out<- surv_Bastab(core, DeathInformation = deathinformation, LatestDate = '2020-12-31', 
                    OtherCovars = c('FirstHoldingInstitution','LastHoldingInstitution'), ExcludeStillBirth = TRUE)
  expect_named(out, c("AnimalAnonID", "binSpecies", "Class", "Order", "Family", "CommonName", "Birth.Date", "Min.Birth.Date", "Max.Birth.Date", "Entry.Date", "Depart.Date", 'Entry.Type', 'Depart.Type', 'FirstHoldingInstitution', 'LastHoldingInstitution'))
  expect_true(max(out$Depart.Date)<=lubridate::as_date('2020-12-31'))
})
