# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Sur_xx works", {
  Lx = matrix(c(seq(1,0,by = -0.1), 1,seq(0.5,0,length.out = 10)),nrow =2)
  out <- Sur_xx(Lx, xv = c(0:10), xx = 0.1)
  expect_named(out, c("L", "Lower", "Upper"))
  expect_true(is.numeric(out$L))
})
