# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_LRS returns expected outputs", {
  ages <- 1:10
  lx <- rep(0.9, 10)
  mx <- c(rep(0, 2), rep(0.5, 6), rep(0, 2))
  names(lx) <- names(mx) <- ages
  
  ReproData <- data.frame(
    AnimalAnonID = sample(1000:2000, 300, TRUE),
    ParentAnonID = sample(1:50, 300, TRUE),
    ParentAge = sample(1:10, 300, TRUE),
    Probability = runif(300, 80, 100)
  )
  
  AnimalData <- data.frame(
    AnimalAnonID = 1:50,
    DepartType = "D",
    DepartDate = as.Date("2020-01-01") + sample(4000:5000, 50),
    BirthDate = as.Date("2000-01-01")
  )
  
  res <- Rep_LRS(ReproData, AnimalData, lx, mx)
  expect_true(res$summary$analyzed)
  expect_true(is.numeric(res$summary$GrowthRate))
  expect_true(is.numeric(res$summary$LRS_expected))
  expect_length(res$summary$ReproductiveValue, length(lx)-1)
})
