# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Sur_out works", {
  PlotDir = paste0(tempdir(check = TRUE),'/temp')
  dir.create(PlotDir)
  data(toy_core)
  data(toy_deathinformation)
  out <- Sur_ana(toy_core,  DeathInformation = toy_deathinformation, Models = "GO", Shape = "simple",
                 niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
  out <- Sur_out(out, ncpus = 3, PlotDir = PlotDir)
  expect_named(out, c("summary","metrics",  "bastaRes", "DICmods", 'KM_estimator', "bastatab", "check", 'relex_from0', 'Sur5', 'Sur1', 'Sur1m'))
  expect_named(out$check, c('Gof_KM_coeff1', 'Gof_KM_coeff2', 'LxatMLE', 'LEmaxOage', 'KMMinLx', 'Gof_Martingal_KM' , 'Gof_Martingal_test'))
  expect_named(out$relex_from0, c("Age", "RemLExp", "Lower", "Upper"))
  expect_true(is.numeric(out$relex_from0$Upper))
  expect_true(is.numeric(out$relex_from0$Age))
  expect_true(is.numeric(out$relex_from0$RemLExp))
  expect_true(is.numeric(out$relex_from0$Lower))
  expect_true(out$relex_from0$Lower[1]<out$relex_from0$RemLExp[1])
  expect_true(out$relex_from0$RemLExp[1]<out$relex_from0$Upper[1])
  expect_named(out$Sur5, c("Age", "Lower",  "Upper", "Sur"))
  expect_true(is.numeric(out$Sur5$Lower))
  expect_true(is.numeric(out$Sur5$Sur))
  out <- Sur_out(out, ncpus = 3, PlotDir = PlotDir)
  
  unlink(PlotDir, recursive = TRUE)
})
