# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_season works with sufficient data", {
  Data <- data.frame(
    Offspring_BirthDate = as.Date("2020-01-01") + sample(0:364, 100, replace = TRUE),
    Offspring_Inst = sample(1:5, 100, replace = TRUE)
  )
  Institution <- data.frame(
    AnonInstitutionID = 1:5,
    Latitude = c(-45, -20, 10, 30, 60)
  )
  
  out <- Rep_season(Data, Institution, MinNBirth = 5, Hemisphere = c("North", "South"))
  
  expect_named(out, c("summary", "monthly_table"))
  expect_true("North" %in% names(out$summary))
  expect_true(out$summary$North$analyzed)
  expect_gt(out$summary$North$Nbirth, 0)
})
