# WARNING - Generated by {fusen} from dev/flat_growth.Rmd: do not edit by hand # nolint: line_length_linter.

z1 = c(rnorm(95,4,1), runif(5,100,1000))
x1 = c(rnorm(100,4,2))

test_that("Gro_Rout_quan error", {
  expect_error(Gro_Rout_quan("text", x1))
  expect_error(Gro_Rout_quan(z1, x1, minq = 1) , regexp = "minq must be a proportion between 0 and 1")
})

test_that("Gro_Rout_quan works", {
  expect_true(sum(Gro_Rout_quan(z1, x1, minq = 0.05)) >= 90)
 expect_true(sum(Gro_Rout_quan(z1, x1, minq = 0.05, type = "lower")) >= 95)
 expect_true(sum(Gro_Rout_quan(z1, x1, minq = 0.05, type = "upper")) >= 95)
})
