# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_littersize works", {
data(toy_core)
data(toy_collection)
data(toy_parent)

  
  Data <- Rep_prepdata (coresubset = toy_core, offspring = toy_core, 
                        toy_collection, toy_parent, 
                        MinNRepro = 1, MinNPaRepro = 1,
                        BirthType_parent = "All", BirthType_offspring = "All" )
  out <- Rep_littersize(Data$ReproData, MinNLitter =2,
                        NDay = 7)
  
  expect_named(out, c("summary", "littSizeDf", "littSizeTab", "littSizeperAge"))
  expect_named(out$summary, c('NOffsp_prob', 'NParent_prob', 'NReprEvent', 'analyzed', 'error', 'Nerr', 'MeanLittSize', 'MedLittSize', 'SELittSize', 'MinLittSize', 'MaxLittSize'))
  expect_named(out$littSizeTab, c("litterSize", "N", "prop"))
  expect_named(out$littSizeDf, c('MotherAnonID', 'InstitutionAnonID', 'litterSize', 'MeanBirthDate', 'Mother_Age', 'OffspringAnonID', 'FatherAnonID', 'Father_Age'))
  expect_named(out$littSizeperAge, c('Mother_Age', 'MeanlittSize', 'SDlittSize', 'SElittSize', 'Nlitter'))
  expect_equal(round(out$summary$MeanLittSize, 2), round(mean(out$littSizeDf$litterSize), 2))
  expect_equal(out$summary$NReprEvent, 14)
  expect_equal(nrow(out$littSizeDf), out$summary$NReprEvent)
  expect_equal(nrow(out$littSizeTab), 1)
  expect_equal(nrow(out$littSizeperAge),10)
})
