# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Handles insufficient growth data", {
  dummy <- data.frame(
    AnimalAnonID = 1,
    BirthDate = Sys.Date(),
    BirthObserved = "YES",
    BirthDateEstimateType = "Estimated",
    BirthUncertainty =0)
  
  result <- Rep_weight1strepro(
    AnimalData = dummy,
    parent = data.frame(ParentAnonID = 1, AnimalAnonID = 1, Probability = 100),
    GrowthData = data.frame(
      AnimalAnonID = 1,
      MeasurementDate = Sys.Date(),
      MeasurementValue = 5,
      MeasurementType = "Live weight",
      RecordType = "",
  MeasurementDateEstimateStart = as.Date("2014-12-01"),
  MeasurementDateEstimateEnd = as.Date("2015-02-01")
   ), Taxa = "Reptilia"
  )
  
  expect_false(result$summary$analyzed)
  expect_type(result$summary$error, "character")
})
