# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_pattern runs and returns valid output", {
  df <- data.frame(
    AnimalAnonID = sample(1:100, 500, replace = TRUE),
    ParentAnonID = sample(1:50, 500, replace = TRUE),
    Probability = runif(500, 50, 100),
    ParentAge = sample(3:20, 500, replace = TRUE)
  )
  
  res <- Rep_pattern(df)
  expect_true("summary" %in% names(res))
  expect_true("model" %in% names(res))
  expect_true(res$summary$analyzed)
  expect_s3_class(res$model, "glm")
})
