# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_birthinterval works with valid data", {
  df <- data.frame(
    ParentAnonID = rep("F1", 4),
    Offspring_BirthDate = as.Date(c("2010-01-01", "2011-01-01", "2012-01-01", "2013-01-01")),
    ParentType = "Dam",
    Probability = 95
  )
  
  out <- Rep_birthinterval(df, MinNInterval = 2)
  expect_type(out, "list")
  expect_named(out, c("intervals_df", "interval_tab", "summary"))
  expect_s3_class(out$intervals_df, "data.frame")
  expect_true(out$summary$NInterval >= 2)
  expect_equal(out$summary$error, "")
})

test_that("Rep_birthinterval returns error if not enough intervals", {
  df <- data.frame(
    ParentAnonID = rep("F2", 2),
    Offspring_BirthDate = as.Date(c("2020-01-01", "2020-01-03")),
    ParentType = "Dam",
    Probability = 90
  )
  out <- Rep_birthinterval(df, MinNInterval = 3)
  expect_true(!is.null(out$summary$error))
  expect_null(out$interval_tab)
})

test_that("Rep_birthinterval filters by ParentType and Probability", {
  df <- data.frame(
    ParentAnonID = rep("F3", 3),
    Offspring_BirthDate = as.Date(c("2011-01-01", "2012-01-01", "2013-01-01")),
    ParentType = c("Dam", "Sire", "Dam"),
    Probability = c(95, 99, 60)
  )
  out <- Rep_birthinterval(df, ParentPerc = 80, MinNInterval = 1)
  expect_true(all(out$intervals_df$ParentType == "Dam"))
  expect_true(all(out$intervals_df$Probability >= 80))
})
