# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

Lx = matrix(c(seq(1,0,by = -0.1), 1,seq(0.5,0,length.out = 10)),nrow =2)
test_that("Sur_relex works", {
  out <- Sur_relex(Lx, dx = 1, xv = c(0:10))
  expect_named(out, c("Age", "RemLExp", "Lower", "Upper"))
  expect_true(is.numeric(out$RemLExp))
})
