# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_agemat returns valid structure with complete input", {
  df <- data.frame(
    ParentAnonID = rep(c("F1", "F2", "F3"), each = 3),
    ParentAge = c(3.1, 4.2, 6.0, 2.8, 4.1, 5.7, 3.0, 6.0, 8.5),
    GlobalStatus = c("Dead", "Dead", "Dead", "Alive", "Alive", "Alive", "Dead", "Dead", "Dead")
  )
  
  result <- Rep_agemat(df)
  
  expect_s3_class(result, "tbl_df")
  expect_named(result, c('age1RepIC', 'age1RepMean', 'age1RepMed', 'age1RepOldest', 'age1RepQuant', 'age1RepSd', 'age1RepYoungest', 'ageOldRepIC', 'ageOldRepMean', 'ageOldRepMed', 'ageOldRepQuant', 'ageOldRepSd', 'ageRepIC', 'ageRepMean', 'ageRepMed', 'ageRepQuant', 'ageRepSd', 'N_birth_agemat', 'N_par_agemat', 'N_parDead_agemat', 'ReproLifespanMax', 'ReproLifespanMean', 'ReproLifespanMed', 'ReproLifespanQuant', 'ReproLifespanSd'),
               ignore.order = TRUE)
  
  expect_equal(result$N_par_agemat, 3)
  expect_equal(result$N_parDead_agemat, 2)
  expect_equal(result$N_birth_agemat, 9)
  
  expect_type(result$age1RepIC, "list")
  expect_type(result$ageRepQuant, "list")
  expect_type(result$ReproLifespanQuant, "list")
  expect_true(!is.na(result$age1RepMean))
  expect_true(result$ReproLifespanMax >= 0)
})

test_that("Rep_agemat handles missing values", {
  df <- data.frame(
    ParentAnonID = c("A", "A", "B", "B", "C"),
    ParentAge = c(NA, 4.5, 5.0, NA, 6.2),
    GlobalStatus = c("Dead", "Dead", "Alive", "Alive", "Dead")
  )
  
  result <- Rep_agemat(df)
  
  expect_equal(result$N_par_agemat, 3)
  expect_true(is.na(result$age1RepMean) == FALSE)
  expect_true(is.numeric(result$ReproLifespanMed))
})


test_that("Rep_agemat handles all living individuals", {
  df <- data.frame(
    ParentAnonID = c("A", "A", "B", "C", "C"),
    ParentAge = c(2.5, 4.5, 3.1, 5.6, 6.1),
    GlobalStatus = rep("Alive", 5)
  )
  
  result <- Rep_agemat(df)
  
  expect_equal(result$N_par_agemat, 3)
  expect_equal(result$N_parDead_agemat, 0)
  expect_true(is.na(result$ageOldRepMean))
  expect_true(is.na(result$ReproLifespanMed))
})

test_that("Confidence intervals are properly computed", {
  df <- data.frame(
    ParentAnonID = rep(c("F1", "F2"), each = 2),
    ParentAge = c(3, 5, 6, 7),
    GlobalStatus = c("Dead", "Dead", "Dead", "Dead")
  )
  
  result <- Rep_agemat(df)
  
  ci <- unlist(result$age1RepIC)
  expect_length(ci, 2)
  expect_true(ci[1] < result$age1RepMean && ci[2] > result$age1RepMean)
})
