# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Sur_age works", {
  Lx = matrix(c(seq(1,0,by = -0.1), 1,seq(0.5,0,length.out = 10)),nrow =2, byrow =T)
  out <- Sur_age(Lx,  Nyear = 5, xv = c(0:10))
  expect_named(out, c("Age", "Lower", "Upper", "Sur"))
  expect_true(is.numeric(out$Sur))
  expect_equal(nrow(out), 6)
})
