# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Sur_ana works", {
  data(toy_core)
  data(toy_deathinformation)
  out <- Sur_ana(toy_core, DeathInformation = toy_deathinformation, Models = "GO", Shape = "bathtub",
                 niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3,
                 LastDead = TRUE)
  expect_named(out, c("summary", "metrics", "bastaRes", "DICmods", 'KM_estimator', 'bastatab'))
  expect_named(out$DICmods, c("Models",  "DIC"))
  expect_equal(nrow(out$DICmods),1)
  expect_named(out$summary, c('NSelect', 'NUncertdeath', 'NBasta', 'Ndead', 'Nrc', 'N8090', 'N9000', 'N0010', 'N1020', 'N2030', 'QBD10', 'QBD50', 'QBD90', 'BDincert', 'maxAge', 'maxAlive', 'lxMin', 'outLev', 'model', 'analyzed', 'Nerr', 'error'))
  #expect_true(out$summary$analyzed )
  expect_true(is.numeric(out$summary$NSelect ))
  expect_true(is.numeric(out$summary$NBasta ))
  expect_true(is.numeric(out$summary$Ndead ))
  expect_true(is.numeric(out$summary$maxAge ))
  expect_true(is.numeric(out$summary$maxAlive))
  expect_true(is.numeric(out$summary$lxMin ))
  expect_true(is.numeric(out$summary$outLev ))
  expect_true(is.numeric(out$summary$Nerr ))
})


test_that("Sur_ana works2", {
  data(toy_core)
  data(toy_deathinformation)
  out <- Sur_ana(toy_core, DeathInformation = toy_deathinformation, Models = "GO", Shape = "bathtub",
                 niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3,
                 OutlLev1 = 100,MaxNSur=1000,
                 LastDead = TRUE)
  expect_named(out, c("summary", "metrics", "bastaRes", "DICmods", 'KM_estimator', 'bastatab'))
})
