# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_main works", {
data(toy_core)
data(toy_collection)
data(toy_parent)
data(toy_weights)
lx = seq(1,0,length.out = 50)
names(lx)= c(1:50)

institution = tibble(AnonInstitutionID = unique(toy_core$FirstHoldingInstitution), Latitude = 57)
out <- Rep_main (coresubset = toy_core, offspring = toy_core, collection = toy_collection, 
                 parent = toy_parent,  institution = institution,
                 GrowthData = toy_weights,core = toy_core,lx = lx,
                 MinNRepro = 1, MinNPaRepro = 1,
                 BirthType_parent = "Captive", BirthType_offspring = "Captive",
                Taxa = "Reptilia"
) 
  expect_type(out, "list")
  expect_true("summary" %in% names(out))
  expect_true(out$summary$sections$agemat)
})
