# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Rep_fert returns valid output with sufficient data", {
  Adults <- data.frame(
    AnimalAnonID = c("A1", "A2", "A3", "A4"),
    Age = c(3, 4, 5, 5)
  )
  
  ReproData <- data.frame(
    ParentAnonID = c("A1", "A2", "A3", "A3"),
    AnimalAnonID = c("O1", "O2", "O3", "O4"),
    ParentAge = c(3, 4, 5, 5),
    Probability = c(90, 85, 95, 85),
    SexType = c("Male", "Female", "Male", "Female")
  )
  
  out <- Rep_fert(ReproData, Adults, AgeMat = 3, MinNPaRep = 1, MinNRep = 1)
  
  expect_type(out, "list")
  expect_named(out, c("summary", "tab"))
  expect_true(out$summary$analyzed)
  expect_true(out$summary$NAdult > 0)
  expect_s3_class(out$tab, "data.frame")
})

test_that("Rep_fert returns error if not enough parents", {
  Adults <- data.frame(
    AnimalAnonID = c("A1", "A2"),
    Age = c(4, 5)
  )
  
  ReproData <- data.frame(
    ParentAnonID = c("A1"),
    AnimalAnonID = c("O1"),
    ParentAge = 4,
    Probability = 95,
    SexType = "Male"
  )
  
  out <- Rep_fert(ReproData, Adults, MinNPaRep = 10, MinNRep = 1)
  
  expect_false(out$summary$analyzed)
  expect_match(out$summary$error, "Not enough parents")
})

test_that("Rep_fert returns error if not enough offspring", {
  Adults <- data.frame(
    AnimalAnonID = c("A1", "A2", "A3"),
    Age = c(4, 5, 6)
  )
  
  ReproData <- data.frame(
    ParentAnonID = c("A1", "A2"),
    AnimalAnonID = c("O1", "O2"),
    ParentAge = c(4, 5),
    Probability = c(90, 90),
    SexType = c("Unknown", "Unknown")  # no sexed offspring
  )
  
  out <- Rep_fert(ReproData, Adults, MinNRep = 5, MinNPaRep = 1)
  
  expect_false(out$summary$analyzed)
  expect_match(out$summary$error, "Not enough offspring")
})
