# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Sur_ple works", {
  entryAge = sample(c(1:10), 200, replace = T)
  data <- data.frame(
    entryAge = entryAge,
    deparAge =  entryAge + sample(c(0:10), 200, replace = T),
    DepartType = sample(c('C', 'D'), 200, replace = T))
  out<-Sur_ple(data)
  expect_named(out, c("Ages", "ple", "event", "Snd"))
  expect_true(min(out$ple)>=0)
  expect_true(max(out$ple)<=1)
})
