# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Find gaps in an integer variable
#' 
#' Looks for gaps within a continuous variable. Values of the variable are rounded and gaps are found if one integer is not represented. Gaps are returned only if the length of the gaps is 20% higher than the starting age of this gap.
#'
#' @param x \code{vector of numeric} variable to analyze
#' @param MaxAlive \code{numeric} Return gaps higher than this maximum, only.
#' @param plot \code{logical} whether to actually plot the histogram
#' @param ... arguments pass to hist()
#'
#' @return
#' A data frame where each line is a gap described by its initial/starting age, its final/ending age and its length
#' 
#' @export
#'
#' @importFrom graphics abline box hist par text
#'
#' @examples
#' x = runif(10,0,40)
#' out<-find_gaps(x,MaxAlive = 5, plot = FALSE)
find_gaps <- function(x,MaxAlive = NA, plot = FALSE,...) {
   # Check correct format for inputs -----------------------------------------------------------------------
 assert_that(is.numeric(x))
  if(is.na(MaxAlive)){
    MaxAlive = max(x)
  }else{
    assert_that(is.numeric(MaxAlive))}
  assert_that(is.logical(plot))
  
  #Round each value of the continuous variable-----------------------------------
  breaks <- floor(min(x, na.rm = TRUE)):ceiling(max(x, na.rm = TRUE))
  hs <- hist(x, breaks = breaks, plot = plot, ...)
  xc <- hs$counts
  xc[hs$counts > 0] <- 1
  
  # Look for gaps ---------------------------------------------------------------
  fin <- FALSE
  i <- 1
  n <- length(xc)
  gaps <- tibble::tibble(iniAge= numeric(1), finAge= numeric(1), Gap= numeric(1))
  while(!fin & i < n) {
    id0st <- which(xc[i:n] == 0)[1]
    if (!is.na(id0st)) {
      id0fin <- which(xc[(i + id0st - 1):n] == 1)[1] - 1
      gaps <- rbind(gaps, c(hs$breaks[i + id0st - 1], 
                            hs$breaks[i + id0st + id0fin - 2], id0fin))
      i <- i + id0st + id0fin - 1
    } else {
      fin <- TRUE
    }
  }
 
  #Return gaps only if the gaps is 20% higher than the starting age of this gap-----
  idgap <- gaps%>%
    dplyr::filter(Gap/iniAge > 0.2 ,
           finAge  >= MaxAlive)
   if (nrow(idgap) > 0 & plot) {abline(v = idgap$iniAge, col = 2)}
  return(idgap)
}
