# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#'  Age from Kaplan-Meier
#' 
#' Estimate Ages at which Lx equals given values from the Kaplan-Meier table. Ages are linearly interpolation between adjacent KM.
#' 
#' @param KM_tab \code{data.frame} The kaplan-Meier table including the columns: *Ages* and *ple*
#' @param Lx \code{numeric vector} Values of Lx for which age is requested
#'
#' @return a data frame including Lx and Age
#' 
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' KM_tab = data.frame( Ages = 1:10,
#'                      ple = sort(runif(10, 0, 1), decreasing = TRUE))
#' out <- KM_age(KM_tab, Lx = c(0.5,0.1))
KM_age <- function(KM_tab, Lx) {
  
  assert_that(is.data.frame(KM_tab))
  assert_that(KM_tab %has_name% c("Ages", "ple"))
  assert_that(is.numeric(Lx))
  assert_that(all(Lx > 0))
  assert_that(all(Lx < 1))
  
  Age_out = c()
  for (lx in Lx){
    if(min(KM_tab$ple)>lx){
      Age_out =  c(Age_out,NA)
    }else{
      a = max(which((KM_tab$ple-lx) >=0))
      if (KM_tab$ple[a]== lx){
        Age_out =  c(Age_out,KM_tab$Ages[a])
        
      }else{
        #Linear extrapolation
        slope = (KM_tab$ple[a]-KM_tab$ple[a+1])/(KM_tab$Ages[a]-KM_tab$Ages[a+1])
        int = KM_tab$ple[a] - slope *(KM_tab$Ages[a])
        Age_out =  c(Age_out,(lx -int)/ slope)
      }
    }
  }
  
  
  out <- tibble::tibble(Lx = Lx, Age = Age_out)
  
  return(out)
}

