# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#'  Lx from Kaplan-Meier
#' 
#' Estimate Survivorship  at given ages from the Kaplan-Meier table.
#' 
#' @param KM_tab \code{data.frame} The kaplan-Meier table including the columns: *Ages* and *ple*
#' @param Age \code{vector of numeric} Ages for which Lx is requested
#'
#' @return a data frame including age, and Lx, giving the interpolated Kaplan-Meier survivorship at the requested ages.
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' KM_tab = data.frame( Ages = 1:10,
#'                      ple = sort(runif(10, 0, 1), decreasing = TRUE))
#' out <- KM_Lx(KM_tab, Age = c(3,6.5))
KM_Lx <- function(KM_tab, Age) {
  
  assert_that(is.data.frame(KM_tab))
  assert_that(KM_tab %has_name% c("Ages", "ple"))
  assert_that(is.numeric(Age))
  assert_that(all(Age > 0))
  
  Lx_out = c()
  for (age in Age){
    if(max(KM_tab$Ages)<age){
      Lx_out =  c(Lx_out,NA)
    }else{
      l = min(which((KM_tab$Ages-age) >=0))
      if (KM_tab$Ages[l]== age){
        Lx_out =  c(Lx_out,KM_tab$ple[l])
        
      }else{
        #Linear extrapolation
        slope = (KM_tab$ple[l]-KM_tab$ple[l-1])/(KM_tab$Ages[l]-KM_tab$Ages[l-1])
        int = KM_tab$ple[l] - slope *(KM_tab$Ages[l])
        Lx_out =  c(Lx_out,age*slope +int)
      }
    }
  }
  out <- tibble::tibble(Age = Age, Lx = Lx_out)
  
  return(out)
}

