# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Estimate Birth Seasonality by Hemisphere
#'
#' Computes descriptive statistics on birth date seasonality across one or both hemispheres,
#' including mean, median, monthly distribution, and concentration of birth dates.It uses julian dates but also
#' Uses circular statistics to account for the periodic nature of time (day of year). The function aligns hemispheres based on institutional latitude.
#'
#' @param Data A \code{data.frame} of reproductive records with columns:
#' \describe{
#'   \item{\code{Offspring_BirthDate}}{Date of birth (class \code{Date}).}
#'   \item{\code{Offspring_Inst}}{Institution ID where the birth occurred.}
#' }
#' @param Institution A \code{data.frame} with:
#' \describe{
#'   \item{\code{AnonInstitutionID}}{Institution anonymous ID.}
#'   \item{\code{Latitude}}{Latitude of the institution (used to assign hemisphere).}
#' }
#' @param MinNBirth \code{numeric}. Minimum number of births required to run analysis for each group (default = 10).
#' @param Hemisphere \code{character}. Which hemisphere(s) to analyze. One or more of:
#' \code{"North"}, \code{"South"}, \code{"All"} (default = "All").
#' 
#' 
#' @return A named \code{list} with:
#' \describe{
#'   \item{\code{summary}}{A list of statistics by hemisphere:
#'     \itemize{
#'       \item{\code{Nbirth}}: Number of births considered
#'       \item{\code{MeanDayOfYear}}: Mean day of the year (linear)
#'        \item{\code{MedianDayOfYear}}: Median birth day
#'       \item{\code{L80}}: Range of dates containing 80% of births (linear)
#'       \item{\code{Range}}: Full range of birth days (linear)
#'       \item{\code{MeanCircularDayOfYear}}: Mean date on the circular scale (0–365)
#'      \item{\code{CircularRange80}}: Circular 80% quantile range (converted to days)
#'       \item{\code{RangeCircular}}: Full range of circular birth dates (in days)
#'       \item{\code{analyzed}}: Logical indicating whether results are valid
#'       \item{\code{error}}: Message in case of insufficient data
#'     }}
#'   \item{\code{monthly_table}}{A table of monthly birth counts and proportions for each hemisphere}
#' }
#'
#' @importFrom assertthat assert_that
#' @importFrom dplyr filter mutate left_join count
#' @importFrom lubridate yday month
#' @importFrom circular circular mean.circular quantile.circular
#' @importFrom glue glue
#' @export
#' @examples
#'
#' # Example with simulated data
#' data_births <- data.frame(
#'   Offspring_BirthDate = as.Date("2020-01-01") + sample(0:364, 50, replace = TRUE),
#'   Offspring_Inst = sample(LETTERS[1:3], 50, replace = TRUE)
#' )
#' institutions <- data.frame(
#'   AnonInstitutionID = LETTERS[1:3],
#'   Latitude = c(45, -33, 10)
#' )
#'
#' res <- Rep_season(data_births, institutions, MinNBirth = 10, Hemisphere = c("North", "South"))
#' # View seasonal summary
#' res$summary$North
Rep_season <- function(Data, Institution, MinNBirth = 10, Hemisphere = "All") {
  # Checks
  assert_that(is.data.frame(Data))
  assert_that(is.data.frame(Institution))
  assert_that(Data %has_name% c("Offspring_BirthDate", "Offspring_Inst"))
  assert_that(Institution %has_name% c("AnonInstitutionID", "Latitude"))
  assert_that(is.numeric(MinNBirth))
  
  # Initialization
  monthly_table = summary = list()
  
  # Prepare institution + hemisphere
  Institution = Institution%>%
    filter(AnonInstitutionID %in% Data$Offspring_Inst)%>%
    mutate(Hemisphere = ifelse(Latitude > 0, "North", "South"))%>%
    rename(Offspring_Inst = AnonInstitutionID)
  
  # Extract julian birth dates and months:
  Data <- Data%>%
    tidyr::drop_na(Offspring_BirthDate, Offspring_Inst)%>%
    mutate( DayOfYear = lubridate::yday(Offspring_BirthDate),
            Month = lubridate::month(Offspring_BirthDate),
            angle_data = circular::circular(2 * pi * DayOfYear / 366)
    )%>%
    left_join( Institution, by = "Offspring_Inst")
  
  
  #Loop over hemisphere studied
  for (ii in Hemisphere) { 
    
    if(ii == "All"){
      Datasea = Data
    }else{
      Datasea = Data%>%
        filter(Hemisphere %in% ii)
    }
    
    # Fill up no analysis case:   
    if (nrow(Datasea) < MinNBirth) {
      
      summary[[ii]] <- list(
        Nbirth = nrow(Datasea),
        MeanDayOfYear = NA,
        MeanCircularDayOfYear = NA,
        MedianDayOfYear = NA,
        L80 = NA,
        Range = NA,
        analyzed = FALSE,
        error <- glue::glue("Not enough births to estimate seasonality (n = {nrow(Datasea)}; min = {MinNBirth})")
      )
      monthly_table[[ii]] <- NULL
      
    }else{
      monthly_table[[ii]] <- Datasea %>%
        count(Month, name = "N") %>%
        mutate(prop = N / sum(N))
      
      # Circular range covering 80% of the density
      quant_10 <- as.numeric(quantile.circular(Datasea$angle_data, 0.10))
      quant_90 <- as.numeric(quantile.circular(Datasea$angle_data, 0.90))
      circ_range_80_days <- round(( c(quant_90, quant_10) * 366) / (2 * pi))
      full_range_days <- round(( range(Datasea$angle_data) * 366) / (2 * pi))
      
      
      summary[[ii]] <- list(
        Nbirth = nrow(Datasea),
        MeanDayOfYear = mean(Datasea$DayOfYear),
        MedianDayOfYear =  median(Datasea$DayOfYear), 
        L80 = quantile(Datasea$DayOfYear, c(0.1,0.9)),
        Range = c(min(Datasea$DayOfYear), max(Datasea$DayOfYear)),
        MeanCircularDayOfYear = as.numeric(circular::mean.circular(Datasea$angle_data)
                                           * 366 / (2 * pi)) %% 366,
        CircularRange80 = circ_range_80_days,
        RangeCircular = full_range_days,
        analyzed = TRUE,
        error = ""
      )
    }
  }
  return(list(summary = summary, monthly_table = monthly_table))
}

