# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Estimate Reproduction Probability, Fertility, and Sex Ratio by Age
#'
#' Computes age-specific reproductive indicators from two sources:
#' (1) a list of all potential reproductive individuals (Adults), and
#' (2) reproduction events (ReproData) with associated parentage probabilities.
#' This function accounts for uncertainty in parentage by using probabilities instead of discrete offspring counts. 
#' Fertility is estimated by summing parentage probabilities (rather than offspring counts), and reproduction probability 
#' is calculated as the maximum parentage probability per parent at each age.
#' 
#' @param ReproData A \code{data.frame} with reproductive links including at least: \code{ParentAnonID}, \code{ParentAge}, \code{Probability}, \code{SexType}, and \code{AnimalAnonID}.
#' @param Adults A \code{data.frame} of all adults available for reproduction, with at least: \code{AnimalAnonID}, \code{Age}.
#' @param AgeMat Numeric. Minimum age at sexual maturity. If \code{NA}, inferred as the youngest age where \code{PRep > 0.05} (default: \code{NA}).
#' @param MinNRep Minimum number of offspring required to compute estimates (default = 10).
#' @param MinNPaRep Minimum number of unique parents required to compute estimates (default = 10).
#'
#' @return A list with:
#' \describe{
#'   \item{\code{summary}}{A named list with overall indicators:
#'     \itemize{
#'       \item{\code{NAdult}}: Total number of adults considered
#'       \item{\code{Nparents}}: Number of individuals with at least one assigned offspring. 
#'                              Note: each parent is counted at each age at which they reproduced
#'       \item{\code{Noffs}}: Number of unique offspring
#'       \item{\code{Noffs_sex}}: Number of offspring with known sex
#'       \item{\code{MeanPrep}}: Mean reproduction probability above age at maturity
#'       \item{\code{MeanFert}}: Mean fertility (offspring per parent)
#'       \item{\code{MeanSR}}: Mean sex ratio (proportion male among sexed offspring)
#'       \item{\code{SEPrep}}, \code{SEFert}, \code{SESR}: Associated standard errors
#'       \item{\code{analyzed}}: Logical. Indicates whether the analysis was successfully completed
#'       \item{\code{error}}: Message in case of insufficient data or early termination
#'     }
#'   }
#'   \item{\code{tab}}{A \code{data.frame} of per-age reproductive indicators: \code{ParentAge}, \code{Fert}, \code{PRep}, \code{SR}, their associated standard errors, and 95% confidence interval bounds (\code{FertLower}, \code{FertUpper}, etc.).}
#' }
#'
#'
#' @importFrom assertthat assert_that
#' @importFrom dplyr filter group_by mutate summarize ungroup count distinct left_join rename n_distinct full_join
#' @importFrom stats sd
#' @importFrom glue glue
#' @export
#' @examples
#' adults <- data.frame(AnimalAnonID = c("A1", "A2", "A3", "A4"), Age = c(3, 4, 5, 4))
#' repro <- data.frame(
#'   ParentAnonID = c("A1", "A2", "A3", "A3"),
#'   AnimalAnonID = c("O1", "O2", "O3", "O4"),
#'   ParentAge = c(3, 4, 5, 5),
#'   Probability = c(90, 80, 95, 85),
#'   SexType = c("Male", "Female", "Male", "Female")
#' )
#' Rep_fert(repro, adults, AgeMat = 3)
#'
#'
#'
#' #Example with ZIMS data
#' data(toy_core)
#' data(toy_collection)
#' data(toy_parent)
#'
#' #prepare Data
#' Data <- Rep_prepdata (coresubset = toy_core, offspring = toy_core, toy_collection, toy_parent,
#'                       MinNRepro = 1, MinNPaRepro = 1,
#'                       BirthType_parent = "All",
#'                       BirthType_offspring = "All" )
#' #Estimate reproductive statistics per age
#' Rep_fert(Data$ReproData, Data$Adults)
#'
Rep_fert  <- function(ReproData, Adults, AgeMat = NA, 
                      MinNRep = 10, MinNPaRep = 10) {
  
  # Checks----------------------------------------------------------------------
  assert_that(is.data.frame(ReproData), is.data.frame(Adults))
  assert_that(ReproData %has_name% c("ParentAnonID", "ParentAge", "Probability", "SexType", "AnimalAnonID"))
  assert_that(Adults %has_name% c("AnimalAnonID", "Age"))
  assert_that(is.numeric(AgeMat) || is.na(AgeMat))
  assert_that(is.numeric(MinNRep), is.numeric(MinNPaRep))
  
  # Output initialization ----------------------------------------------------------
  fert_tab <- NULL
  summary <- list(
    NAdult = 0, Nparents = 0, Noffs = 0, Noffs_sex = 0,
    MeanPrep = NA, MeanFert = NA, MeanSR = NA,
    SEPrep = NA, SEFert = NA, SESR = NA,
    analyzed = FALSE, error = ""
  )
  
  # Get the number of potential reproductive individuals by age ---------------------------
  agemat = ifelse(is.na(AgeMat), 0, AgeMat)
  AD = Adults%>%
    filter(Age >= agemat)%>%
    #filter(contra == FALSE)%>%
    mutate(Age = floor(Age))%>%
    dplyr::count(Age, name = "Nads") %>%
    dplyr::rename(ParentAge = Age)
  
  # Per-individual reproductive summaries
  fert_df = ReproData %>%
    mutate(ParentAge = floor(ParentAge))%>%
    group_by(ParentAge, ParentAnonID)%>%
    summarize (PRep_Par = max(Probability, na.rm = TRUE)/100,
               FertRate_Par = sum(Probability, na.rm = TRUE)/100,
               Nfemale = sum(Probability[SexType == "Female"], na.rm = TRUE)/100,
               Nmale = sum(Probability[SexType == "Male"], na.rm = TRUE)/100,
               .groups = "drop"
    )
  # Counts -----------------------------------------------------------------
  summary$NAdult = sum(AD$Nads)
  summary$Nparents = nrow(fert_df)
  summary$Noffs_sex= n_distinct(ReproData$AnimalAnonID[ReproData$SexType %in% c("Male", "Female")])
  summary$Noffs = n_distinct(ReproData$AnimalAnonID)
  
  if (summary$Nparents < MinNPaRep) {
    summary$error <- glue("Not enough parents (n = {summary$Nparents}; min = {MinNPaRep})")
    return(list(summary = summary, tab = fert_tab))
  }
  
  if (summary$Noffs < MinNRep) {
    summary$error <- glue("Not enough offspring (n = {summary$Noffs}; min = {MinNRep})")
    return(list(summary = summary, tab = fert_tab))
  }
  
  # Estimate statistics -----------------------------------------------------------
  # Age-level summary
  fert_tab =  fert_df %>% 
    group_by(ParentAge)%>%
    summarize (
      Npar = n(),
      Fert = mean(FertRate_Par, na.rm = TRUE),
      FertSD = ifelse(nrow(cur_group())==1,0, sd(FertRate_Par, na.rm = TRUE)),
      FertSE = FertSD/ sqrt(Npar),
      PRep = sum(PRep_Par) ,
      SR = sum(Nmale, na.rm = TRUE) / (sum(Nfemale + Nmale, na.rm = TRUE)),
      SRSE = sqrt(SR * (1 - SR) / (sum(Nfemale + Nmale, na.rm = TRUE))),
      .groups = "drop"
    )%>%select(-FertSD)%>%
    full_join(AD, by = c("ParentAge"))%>%
    mutate(           Npar = ifelse(is.na(Npar),0,Npar),
                      Fert = ifelse(is.na(Fert),0,Fert),
                      FertSE = ifelse(is.na(FertSE),0,FertSE),
                      PRep = ifelse(is.na(PRep),0,PRep),
                      PRep = PRep / Nads,
                      PRepSE =  sqrt(PRep * (1 - PRep))/ sqrt(Nads),
                      FertLower = pmax(0, Fert - 1.96 * FertSE),
                      FertUpper = Fert + 1.96 * FertSE,
                      PRepLower = pmax(0, PRep - 1.96 * PRepSE),
                      PRepUpper = pmin(1, PRep + 1.96 * PRepSE),
                      SRLower = pmax(0, SR - 1.96 * SRSE),
                      SRUpper = pmin(1, SR + 1.96 * SRSE),
    )%>%arrange(ParentAge)
  
  Sex = ReproData %>%
    filter(SexType %in% c("Male", "Female"))%>%
    select(SexType, AnimalAnonID)%>%
    distinct()%>%
    count(SexType)
  
  # Determine AgeMat if NA
  if (is.na(AgeMat)) {
    if(any(fert_tab$PRep > 0.025)){
      AgeMat <- min(fert_tab$ParentAge[fert_tab$PRep > 0.025], na.rm = TRUE)
    }else{
      summary$error <- glue("Age at sexual maturity is unknown")
      return(list(summary = summary, tab = fert_tab))
      
    }
  }
  
  # Final mean-level summaries
  summary$MeanPrep <- sum(fert_df$PRep_Par[fert_df$ParentAge>=AgeMat]) / sum(fert_tab$Nads[fert_tab$ParentAge>=AgeMat])
  summary$MeanFert <- mean(fert_tab$Fert, na.rm = TRUE)
  summary$MeanSR <-  Sex$n[Sex$SexType == "Male"] / sum(Sex$n)
  summary$SEPrep <- sqrt(summary$MeanPrep * (1 - summary$MeanPrep) /
                           sum(fert_tab$Nads[fert_tab$ParentAge >= AgeMat], na.rm = TRUE))
  summary$SEFert <- sd(fert_tab$Fert, na.rm = TRUE) / sqrt(nrow(fert_tab))
  summary$SESR <- sqrt(summary$MeanSR * (1 - summary$MeanSR) /sum(Sex$n))
  
  summary$analyzed <- TRUE
  #We cannot estimate Median as they will be biased by low probability due to MULT
  
  
  
  return(list(summary = summary, tab = fert_tab))
  
}

