# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Estimate Observed and Expected Lifetime Reproductive Success (LRS) and Demographic Indicators
#'
#' This function computes both observed and predicted lifetime reproductive success (LRS). Observed LRS of individuals is based on reproductive data from dead individuals only. Expected LRS and demographic indicators including generation time, population growth rate, and reproductive value are estimated using a Leslie matrix from survivorship (`lx`) and fertility (`mx`).
#'
#' @param ReproData A \code{data.frame} with at least: \code{AnimalAnonID}, \code{ParentAnonID}, \code{ParentAge}, and \code{Probability}.
#' @param AnimalData A \code{data.frame} with \code{AnimalAnonID}, \code{DepartType}, \code{DepartDate}, \code{BirthDate}.
#' @param lx A named numeric vector of survivorship. Names must correspond to age in years.
#' @param mx A named numeric vector of age-specific mean reproductive output. Names must correspond to age in years.
#' @param ParentPerc Numeric. Minimum parentage probability to retain a reproductive event. Default: 80.
#' @param MinN Integer. Minimum number of individuals with observed LRS required. Default: 20.
#'
#'
#' @return A list containing:
#' \describe{
#'   \item{\code{summary}}{Descriptive statistics of observed LRS}
#'   \item{\code{LRS_table}}{Individual observed LRS values}
#'   \item{\code{LRS_expected}}{Expected LRS: sum(lx * mx) - also called net reproductive rate R0}
#'   \item{\code{GenerationTime_age}}{Mean age of reproduction weighted by lx * mx}
#'   \item{\code{ReproductiveValue}}{Relative age-specific contribution to the population}
#'   \item{\code{StableAgeDistribution}}{Stable age distribution at equilibrium}
#'   \item{\code{GrowthRate}}{Dominant eigenvalue (lambda)}
#'   \item{\code{GenerationTime}}{Estimated from (ln(lambda)/ln(R0))}
#' }
#'
#' @importFrom assertthat assert_that
#' @importFrom dplyr filter mutate select rename left_join group_by summarise n_distinct
#' @importFrom stats sd quantile
#' @importFrom glue glue
#' @export
#' @examples
#' ages <- 1:20
#' lx <- exp(-0.05 * ages)
#' mx <- dnorm(ages, mean = 10, sd = 3)
#' names(lx) <- names(mx) <- ages
#'
#' ReproData <- data.frame(
#'   AnimalAnonID = sample(10000:20000, 1000, TRUE),
#'   ParentAnonID = sample(1:100, 1000, TRUE),
#'   ParentAge = sample(1:20, 1000, TRUE),
#'   Probability = runif(1000, 60, 100)
#' )
#'
#' AnimalData <- data.frame(
#'   AnimalAnonID = 1:100,
#'   DepartType = "D",
#'   DepartDate = as.Date("2020-01-01") + sample(4000:7000, 100),
#'   BirthDate = as.Date("2000-01-01")
#' )
#'
#' res <- Rep_LRS(ReproData, AnimalData, lx, mx)
#' str(res, max.level = 1)
Rep_LRS <- function(ReproData, AnimalData, lx = NULL, mx = NULL, ParentPerc = 80, MinN = 20) {
  # Checks
  assert_that(is.data.frame(ReproData), is.data.frame(AnimalData))
  assert_that(ReproData %has_name% c("AnimalAnonID", "ParentAnonID", "ParentAge", "Probability"))
  assert_that(AnimalData %has_name% c("AnimalAnonID", "DepartType", "DepartDate", "BirthDate"))
  
  if(!is.null(lx) & !is.null(mx)){
  assert_that(is.numeric(lx), is.numeric(mx))
  assert_that(all(names(lx) %in% names(mx)), msg = "lx and mx must be defined on the same age classes")
  }
  assert_that(is.numeric(ParentPerc), is.numeric(MinN))
  
  #Select only dead individuals
  AnimalData = AnimalData%>%
    filter(DepartType =="D")%>%
    mutate(lifespans = as.numeric(DepartDate - BirthDate) / 365.25)%>%
    select(AnimalAnonID, lifespans)%>%
    rename(ParentAnonID = AnimalAnonID)
  
  # Clean reproductive data
  reproLRS <- ReproData %>%
    left_join(AnimalData, by = "ParentAnonID")%>%
    tidyr::drop_na(lifespans)%>%
    filter(Probability >= ParentPerc) %>%
    group_by(ParentAnonID, lifespans) %>%
    summarise(LRS_obs = dplyr::n_distinct(AnimalAnonID), .groups = "drop") %>%
    rename(AnimalAnonID = ParentAnonID)
  
  # Check sample size
  if (nrow(reproLRS) < MinN) {
    return(list(
      summary = list(analyzed = FALSE, 
                     error = glue::glue("Too few individuals with LRS data (n = {nrow(reproLRS)} < {MinN})"),
    N_LRS = nrow(reproLRS),
    Mean_LRS = NA,
    Median_LRS = NA,
    Sd_LRS = NA,
       GenerationTime = NA,
      ReproductiveValue = NA,
      GrowthRate = NA,
      LRS_expected = NA,
    GenerationTime_age = NA),
      LRS_table = NULL
    ))
  }
  
  # Observed LRS statistics
  LRS_vals <- reproLRS$LRS_obs
  summary <- list(
    analyzed = TRUE,
    N_LRS = length(LRS_vals),
    Mean_LRS = mean(LRS_vals),
    Median_LRS = median(LRS_vals),
    Sd_LRS = sd(LRS_vals),
    Min = min(LRS_vals),
    Max = max(LRS_vals),
    Quant = quantile(LRS_vals, c(0.025, 0.975)),
    error = "",
    GenerationTime = NA,
    ReproductiveValue = NA,
     GrowthRate = NA
  )
  
   if(!is.null(lx) & !is.null(mx)){
  # Align ages
  ages <- sort(as.numeric(names(lx)))
  lx <- lx[as.character(ages)]
  mx <- mx[as.character(ages)]
  lx[is.na(lx)]=0
  mx[is.na(mx)]=0
  sx = lx[2:length(lx)]/lx[1:(length(lx)-1)]
  
  # Expected LRS and generation time
  expected_LRS <- sum(lx * mx, na.rm = TRUE)
  GenerationTime_age <- sum(ages * lx * mx, na.rm = TRUE) / expected_LRS
  
  # Leslie matrix
  Lmat <- matrix(0, nrow = length(ages)-1, ncol = length(ages)-1)
  Lmat[1, ] <- mx[-length(ages)]
  diag(Lmat[-1, -ncol(Lmat)]) <- sx[-c(length(ages),length(ages)-1)]
  Lmat[length(ages)-1,length(ages)-1 ] <- sx[length(ages)-1]
  
  eig <- eigen(Lmat)
  summary$GrowthRate <- Re(eig$values[1])
  sad <- Re(eig$vectors[, 1])
 rv <- Re(eig$vectors[, 2])
  summary$sad <- sad / sum(sad)
  summary$ReproductiveValue <- rv / rv[1]
  summary$GenerationTime <- log(expected_LRS)/log(summary$GrowthRate)
    summary$LRS_expected = expected_LRS
     summary$GenerationTime_age = GenerationTime_age
   }
  return(list(
    summary = summary,
    LRS_table = reproLRS
   
  ))
}
