# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Age of reproduction
#' 
#' Returns summary statistics for ages of reproduction, including age at first, last, and overall reproductive events.
#'
#' @param ReproData \code{data frame} including at least the columns *ParentAnonID*, *ParentAge* and *GlobalStatus*.
#'
#' @return A \code{tibble} with the following named elements:
#'
#' \describe{
#'   \item{N_par_agemat}{Number of unique parents with at least one recorded offspring.}
#'   \item{N_parDead_agemat}{Number of parents with a known death status (\code{GlobalStatus == "Dead"}). Used for reproductive lifespan calculations.}
#'   \item{N_birth_agemat}{Total number of reproductive events (rows in \code{ReproData}).}
#'
#'   \item{age1RepYoungest}{Minimum observed age at first reproduction (i.e., youngest recorded parent).}
#'   \item{age1RepOldest}{Maximum observed age at first reproduction (i.e., oldest age at first reproduction).}
#'   \item{age1RepMean}{Mean age at first reproduction.}
#'   \item{age1RepSd}{Standard deviation of age at first reproduction.}
#'   \item{age1RepMed}{Median age at first reproduction.}
#'   \item{age1RepIC}{Confidence interval (95%) for mean age at first reproduction, calculated as mean ± 1.96 × SE. Stored as a numeric vector of length 2.}
#'   \item{age1RepQuant}{Quantile range (2.5% and 97.5%) for age at first reproduction.}
#'
#'   \item{ageRepMean}{Mean age across all reproductive events.}
#'   \item{ageRepSd}{Standard deviation of age at reproduction across all events.}
#'   \item{ageRepMed}{Median age at reproduction.}
#'   \item{ageRepIC}{Confidence interval (95%) for mean reproductive age.}
#'   \item{ageRepQuant}{Quantile range (2.5% and 97.5%) for age at reproduction.}
#'
#'   \item{ageOldRep}{Maximum age at last reproduction observed (across all parents).}
#'   \item{ageOldRepMean}{Mean age at last reproduction (among deceased parents only).}
#'   \item{ageOldRepSd}{Standard deviation of age at last reproduction (deceased parents).}
#'   \item{ageOldRepMed}{Median age at last reproduction (deceased parents).}
#'   \item{ageOldRepIC}{Confidence interval (95%) for age at last reproduction.}
#'   \item{ageOldRepQuant}{Quantile range (2.5% and 97.5%) for age at last reproduction.}
#'
#'   \item{ReproLifespanMean}{Mean reproductive lifespan (last - first reproduction), for pares with known death.}
#'   \item{ReproLifespanMed}{Median reproductive lifespan.}
#'   \item{ReproLifespanMax}{Maximum observed reproductive lifespan.}
#'   \item{ReproLifespanSd}{Standard deviation of reproductive lifespan.}
#'   \item{ReproLifespanQuant}{Quantile range (2.5% and 97.5%) of reproductive lifespan.}
#' }
#' 
#' @export
#' @importFrom stats dist median var sd quantile
#'
#' @examples
#' data(toy_core)
#' data(toy_collection)
#' data(toy_parent)
#'
#'
#' #prepare Data
#' Data <- Rep_prepdata (coresubset = toy_core, offspring = toy_core,toy_collection, toy_parent,
#'                       MinNRepro = 1, MinNPaRepro = 1)
#' #Calculate summary for reproductive ages
#' out <- Rep_agemat(Data$ReproData)
#' out
#'
Rep_agemat <- function(ReproData) {
  # Check correct format for inputs -------------------------------------------
  assert_that(is.data.frame(ReproData))
  assert_that(ReproData %has_name% c("ParentAnonID", "ParentAge", "GlobalStatus"))
  
  # Initialize outputs ----------------------------------------------------------
  fertSumm <- tibble(N_par_agemat = 0, N_parDead_agemat = 0, N_birth_agemat = 0, 
                     age1RepYoungest = NA, age1RepOldest = NA,
                     age1RepMean = NA, age1RepSd = NA,  age1RepMed = NA,
                     age1RepIC = NA, age1RepQuant = NA,
                     ageRepMean = NA, ageRepSd= NA, ageRepMed = NA,
                     ageRepIC = NA, ageRepQuant = NA, 
                     ageOldRepMean = NA, ageOldRepSd = NA,  ageOldRepMed = NA,
                     ageOldRepIC = NA, ageOldRepQuant = NA,
                     ReproLifespanMed = NA, ReproLifespanMean = NA,
                     ReproLifespanMax = NA, ReproLifespanQuant = NA) 
  
  # Compute per-individual first and last reproductive ages --------------------------------------------------
  TageMat <-  ReproData%>%
    dplyr::select(ParentAnonID, ParentAge, GlobalStatus)%>%
    group_by(ParentAnonID, GlobalStatus)%>%
    summarize(ageMat = min(ParentAge),
              ageold = max(ParentAge),
              .groups = "drop"
    )%>%
    mutate(ReproLifespan= ageold-ageMat)

  ReproDataD <-  ReproData%>%
    dplyr::select(ParentAnonID, ParentAge, GlobalStatus)%>%
    distinct()
  
  TageMatold = TageMat%>%filter(GlobalStatus == "Dead")
  
  fertSumm$N_par_agemat  = nrow(TageMat)
  fertSumm$N_parDead_agemat  = nrow(TageMatold)
  fertSumm$N_birth_agemat  = nrow( ReproDataD)
  
  # Age at first reproduction
  fertSumm$age1RepYoungest= as.numeric(min(TageMat$ageMat, na.rm = TRUE))
  fertSumm$age1RepOldest = as.numeric(max(TageMat$ageMat, na.rm = TRUE))
  fertSumm$age1RepMean = mean(as.numeric(TageMat$ageMat), na.rm = TRUE)
  fertSumm$age1RepSd = sd(as.numeric(TageMat$ageMat), na.rm = TRUE)
  fertSumm$age1RepIC = list(fertSumm$age1RepMean +
                              c(-1.96, 1.96)*fertSumm$age1RepSd/sqrt(nrow(TageMat)))
  fertSumm$age1RepQuant = list(quantile(as.numeric(TageMat$ageMat), c(0.025,0.975), na.rm = TRUE))
  fertSumm$age1RepMed =  median(as.numeric(TageMat$ageMat), na.rm = TRUE)
  
  # All reproduction events
  fertSumm$ageRepMean = mean(as.numeric(ReproDataD$ParentAge), na.rm = TRUE)
  fertSumm$ageRepSd = sd(as.numeric(ReproDataD$ParentAge), na.rm = TRUE)
  fertSumm$ageRepIC = list(fertSumm$ageRepMean +
                             c(-1.96, 1.96) * fertSumm$ageRepSd / sqrt(nrow(ReproData)))
  fertSumm$ageRepQuant = list(quantile(ReproDataD$ParentAge, c(0.025,0.975), na.rm = TRUE))
  fertSumm$ageRepMed =  median(as.numeric(ReproDataD$ParentAge), na.rm = TRUE)
  
  #Age at last reproduction (only for known-dead individuals)
  fertSumm$ageOldRepMean = mean(as.numeric(TageMatold$ageold), na.rm = TRUE)
  fertSumm$ageOldRepSd = sd(as.numeric(TageMatold$ageold), na.rm = TRUE)
  fertSumm$ageOldRepIC = list(fertSumm$ageOldRepMean + 
                                c(-1.96, 1.96) * fertSumm$ageOldRepSd / sqrt(nrow(TageMatold)))
  fertSumm$ageOldRepQuant = list(quantile(as.numeric(TageMatold$ageold), c(0.025,0.975), na.rm = TRUE))
  fertSumm$ageOldRepMed =  median(as.numeric(TageMatold$ageold), na.rm = TRUE)
  
  
  # Reproductive lifespan (only for known-dead individuals)
  fertSumm$ReproLifespanMed =  median(as.numeric(TageMatold$ReproLifespan), na.rm = TRUE)
  fertSumm$ReproLifespanSd =  sd(as.numeric(TageMatold$ReproLifespan), na.rm = TRUE)
  fertSumm$ReproLifespanMean =  mean(as.numeric(TageMatold$ReproLifespan), na.rm = TRUE)
  if(!is.na( fertSumm$ReproLifespanMean)) {fertSumm$ReproLifespanMax = max(as.numeric(TageMatold$ReproLifespan), na.rm = TRUE)
  }else{fertSumm$ReproLifespanMax =NA}
  fertSumm$ReproLifespanQuant = list(quantile(TageMatold$ReproLifespan, c(0.025,0.975), na.rm = TRUE))
  
  return(fertSumm)
}
