# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Reproductive Summary Master Function
#'
#' Runs all selected reproductive analyses on a dataset of animal records, parentage, movement, collection, and optionally survival, growth, and institution information.
#'
#' @param coresubset A \code{data.frame} of individual-level records including parents. Must include columns: \code{AnimalAnonID}, \code{BirthType}, \code{MaxBirthDate}, \code{MinBirthDate}, \code{DepartDate}, \code{BirthDate}, \code{SexType}, \code{FirstHoldingInstitution}, and \code{GlobalStatus}.
#' @param offspring A \code{data.frame} of individual-level records including offspring. Must include columns: \code{AnimalAnonID}, \code{BirthType}, \code{MaxBirthDate}, \code{MinBirthDate}, \code{DepartDate}, \code{BirthDate}, \code{SexType}, \code{FirstHoldingInstitution}, and \code{GlobalStatus}.
#' @param collection A \code{data.frame} with at least: \code{AnimalAnonID}, \code{ScopeType}, \code{ChangeDate}.
#' @param parent A \code{data.frame} of parentage information including: \code{ParentAnonID}, \code{AnimalAnonID}, \code{Probability}, \code{ParentCollectionScopeType}, \code{OffspringCollectionScopeType}, and \code{ParentOriginType}.
#' @param contraception \code{data.frame}. Contraception records including columns: 
#' \emph{AnimalAnonID}, \emph{Date}, \emph{Status}. (default: \code{NULL}).
#' @param RepSect A character vector of sections to run. Options: \code{"agemat"}, \code{"litter"}, \code{"IBI"}, \code{"fert"}, \code{"season"}, \code{"pattern"}, \code{"LRS"}, \code{"weightrepro"}, \code{"weight1st"}.
#' @param BirthType_parent Filter for parents by birth type ("Captive", "Wild", "All"). Default = "Captive".
#' @param BirthType_offspring Filter for offspring by birth type. Default = "Captive".
#' @param Global Logical; if \code{TRUE}, only use globally scoped records. Default = TRUE.
#' @param MinInstitution Minimum number of institutions required for analysis to proceed. Default = 2.
#' @param MinNRepro Minimum number of reproductive events required. Default = 100.
#' @param MinNPaRepro Minimum number of reproductive parents required. Default = 30.
#' @param ParentPerc Minimum parentage probability (%). Default = 80.
#' @param MinNLitter Minimum number of litters for \code{Rep_littersize}. Default = 20.
#' @param NDay Maximum days between births to consider same litter. Default = 7.
#' @param NMinEvenperAge Minimum number of reproductive events per age class (used in \code{Rep_pattern}). Default = 3.
#' @param MinNSeas Minimum number of births for seasonality analysis. Default = 50.
#' @param institution \code{data.frame} of institution AnonID and hemisphere to evaluate seasonality for seasonality analysis.
#' @param lx A named numeric vector of survivorship (used in \code{Rep_LRS}).
#' @param GrowthData A \code{data.frame} with individual growth measurements including: \code{AnimalAnonID}, \code{MeasurementDate}, \code{MeasurementValue}, \code{MeasurementType}, \code{MeasurementDateEstimateEnd}, \code{MeasurementDateEstimateStart}, and \code{RecordType}. (used in \code{Rep_weightrepro} and \code{Rep_weight1strepro}).
#' @param core A \code{data.frame} with individual-level metadata including:
#' \code{AnimalAnonID}, \code{BirthDate}, \code{BirthObserved}, and \code{BirthDateEstimateType}. The birth date is not necessarily known (used in \code{Rep_weight1strepro}).
#' @param Taxa Character. Taxonomic group. One of: \code{"Mammalia"}, \code{"Aves"}, \code{"Reptilia"},
#' \code{"Amphibia"}, \code{"Chondrichthyes"}, or \code{"Osteichthyes"}.
#' @param maxweight Optional. Numeric. Maximum plausible body mass to retain (defaults to taxon-specific value, used for \code{Rep_weightrepro} and \code{Rep_weight1strepro}).
#' @param MinNImm Numeric. Minimum proportion of immature and mature individuals required (default = 0.2, used in \code{Rep_weight1strepro}).
#' @param UncertBirth Maximum uncertainty tolerated for dates (used in \code{Rep_weightrepro} and \code{Rep_weight1strepro}).
#' @param MinDate \code{character 'YYYY-MM-DD'} Earliest offspring birth date to include data
#' @param RemContra \code{logical}. Whether contraception data should be used to remove individuals under contraception (see details) (default: \code{FALSE}).
#' 
#' @details
#' Contraception: An individual is removed for the rolling year around the dates when it is recorded under Active Contraception.
#'
#' @return A named list with:
#' \describe{
#'   \item{\code{summary}}{General metadata and section-by-section success flags}
#'   \item{\code{agemat}}{(optional) Output from \code{Rep_agemat}}
#'   \item{\code{litter}}{(optional) Output from \code{Rep_littersize}}
#'   \item{\code{IBI}}{(optional) Output from \code{Rep_IBI}}
#'   \item{\code{fert}}{(optional) Output from \code{Fep_fert}}
#'   \item{\code{season}}{(optional) Output from \code{Rep_season}}
#'   \item{\code{pattern}}{(optional) Output from \code{Rep_pattern}}
#'   \item{\code{LRS}}{(optional) Output from \code{Rep_LRS}}
#'   \item{ \code{weightrepro}}{(optional) Output from \code{Rep_weightrepro}}
#'  \item{\code{weight1st}}{(optional) Output from \code{Rep_weight1strepro}
#' }}
#'
#' @export
#' @examples
#' data(toy_core)
#' data(toy_collection)
#' data(toy_parent)
#' data(toy_weights)
#' lx = seq(1,0,length.out = 50)
#' names(lx)= c(1:50)
#'
#' institution = data.frame(
#'   AnonInstitutionID = unique(toy_core$FirstHoldingInstitution), 
#'   Latitude = 57)
#' out <- Rep_main (coresubset = toy_core, offspring = toy_core, collection = toy_collection, 
#'                  parent = toy_parent, institution = institution,
#'                  GrowthData = toy_weights,core = toy_core,lx = lx,
#'                  MinNRepro = 1, MinNPaRepro = 3,
#'                  BirthType_parent = "Captive", BirthType_offspring = "Captive",
#'                 Taxa = "Reptilia"
#' ) 
Rep_main <- function(coresubset, offspring, collection, parent, contraception = NULL,
                      RepSect = c('agemat', 'litter', 'season', 'weight1st',
                                  'pattern', 'LRS',
                                 'IBI', 'fert'),
                      BirthType_parent = "Captive", BirthType_offspring = "Captive", 
                      Global = TRUE, MinInstitution = 2, 
                      MinNRepro = 100,MinNPaRepro = 30,
                      ParentPerc = 80, MinNLitter = 20, NDay = 7,
                      institution = NULL, lx = NULL, 
                      GrowthData = NULL, core = NULL, MinDate = "1980-01-01",
                      NMinEvenperAge = 3,MinNImm=0.2, UncertBirth = 365,
                      maxweight = NULL, Taxa = NULL,
                      MinNSeas = 50, RemContra = FALSE) {
  # Check correct format for inputs ---------------------------------------------
 MinDate = lubridate::as_date(MinDate)
 assert_that(is.data.frame(coresubset))
 assert_that(is.data.frame(offspring))
  assert_that(is.data.frame(collection))
  assert_that(is.data.frame(parent))
  assert_that(is.double(MinInstitution))
 assert_that(all(RepSect %in% c('agemat', 'litter', 'season', 'weight1st','pattern', 'LRS',  'IBI', 'fert')),
             msg =   "Invalid entries in RepSect")
  assert_that(coresubset %has_name% c("AnimalAnonID", 'BirthType', "MaxBirthDate", 
                                      "MinBirthDate", "DepartDate", "BirthDate",
                                      "SexType", "FirstHoldingInstitution"))
   assert_that(offspring %has_name% c("AnimalAnonID", 'BirthType', "MaxBirthDate", 
                                      "MinBirthDate", "DepartDate", "BirthDate",
                                      "SexType", "FirstHoldingInstitution"))
  assert_that(collection %has_name% c("AnimalAnonID", "ScopeType", "ChangeDate"))
  assert_that(parent %has_name% c("ParentAnonID", "ParentCollectionScopeType", 
                                  "OffspringCollectionScopeType", "AnimalAnonID",
                                  "ParentOriginType", "Probability"))
  assert_that(is.character(BirthType_parent))
  assert_that(BirthType_parent %in% c("Captive", "Wild", "All"))
  assert_that(is.character( BirthType_offspring))
  assert_that( BirthType_offspring %in% c("Captive", "Wild", "All"))
  assert_that(is.logical(Global))
  assert_that(is.logical(RemContra))
  
  assert_that(is.numeric(ParentPerc), is.numeric(MinNRepro), is.numeric(MinNPaRepro), is.numeric(MinNLitter), is.numeric(MinNSeas), is.numeric(NDay), is.numeric(NMinEvenperAge), is.numeric(MinNImm))
  assert_that(ParentPerc > 0, MinNRepro > 0, MinNPaRepro > 0, 
              MinNLitter > 0, MinNSeas > 0, NDay > 0, NMinEvenperAge>0, MinNImm>0)
  
if("Season" %in% RepSect){
  assert_that(is.data.frame(Institution))
  assert_that(Institution %has_name% c("AnonInstitutionID", "Latitude"))
}
  
   if('weight1st'  %in% RepSect){
      assert_that(is.data.frame(core))
  assert_that(core %has_name% c("AnimalAnonID", "BirthDate", "BirthObserved", "BirthDateEstimateType", "BirthUncertainty"))
      assert_that( is.data.frame(GrowthData))
  assert_that(GrowthData %has_name% c("AnimalAnonID", "MeasurementDate", "MeasurementValue", "MeasurementType", "RecordType", "MeasurementDateEstimateEnd", "MeasurementDateEstimateStart"))
   }
    out <- list()
  

  # Prepare Reproduction data ----------------------------------------------------
  Datarep <- Rep_prepdata(coresubset = coresubset, offspring = offspring,
                          collection, parent, contraception = contraception,
                          BirthType_parent = BirthType_parent, 
                          BirthType_offspring = BirthType_offspring,
                          MinNRepro = MinNRepro, MinNPaRepro = MinNPaRepro,
                          MinDate = MinDate,
                          Global = Global, RemContra = RemContra)
  out[["summary"]] <- as.list(Datarep$summary)
  out$summary$analyzed <- FALSE
  out$summary$RemContra = RemContra
    out$summary$sections <- list(agemat = FALSE, litter = FALSE, IBI = FALSE,
                                fert= FALSE, season= FALSE, pattern= FALSE, 
                               LRS= FALSE, weight1st= FALSE)  
  if (!Datarep$summary$analyzed || nrow(Datarep$ReproData) == 0) {
    return(out)
  }
  subfert <- Datarep$ReproData
  
  
  if (Datarep$summary$NInst < MinInstitution) {
    out$summary$error <- glue::glue("Only {Datarep$summary$NInst} institution(s)")
    out$summary$Nerr <- 3
    return(out)
  }
  
  AgeMat = NA
  mx = NULL
  ### --- 1. Reproduction and Ages
  if ("agemat" %in% RepSect) {
    out[["agemat"]] <- Rep_agemat(subfert)
    out$summary$sections$agemat <- TRUE
    AgeMat = floor(out[["agemat"]]$summary$age1RepQuant[[1]][1])
  }
  
  ### --- 2. Litter size
  if ("litter" %in% RepSect) {
    out[["litter"]] <- Rep_littersize(subfert,
                                      NDay = NDay,
                                      ParentPercDam = ParentPerc,
                                      ParentPercSire = ParentPerc,
                                      MinNLitter = MinNLitter)
    out$summary$sections$litter <- out[["litter"]]$summary$analyzed
  }
  
  ### --- 3. IBI
  if ("IBI" %in% RepSect) {
    out[["IBI"]] <- Rep_birthinterval(
      ReproData = subfert,
      ParentPerc = ParentPerc,
      MinNInterval = MinNRepro,
      NDay = NDay
    )
    out$summary$sections$IBI <- out[["IBI"]]$summary$analyzed
  }
  
    ### --- 4. Fertility
  if ("fert" %in% RepSect) {
    out[["fert"]] <- Rep_fert(subfert, Datarep$Adults, AgeMat = AgeMat,
                               MinNRep = MinNRepro, MinNPaRep = MinNPaRepro)
    out$summary$sections$fert <- out[["fert"]]$summary$analyzed
    if(out[["fert"]]$summary$analyzed & !is.null(lx)){
      mx = rep(0, length(lx))
      names(mx)= names(lx)
      for(i in 1:nrow(out[["fert"]]$tab)){
      mx[[as.character(out[["fert"]]$tab$ParentAge)[i]]] = out[["fert"]]$tab$Fert[i]*out[["fert"]]$tab$PRep[i]
      }
    }
  }
  
  ### --- 5. Birth Seasonnality
  if ("season" %in% RepSect) {
    out[["season"]] <- Rep_season(subfert, institution,  MinNBirth = MinNSeas,
                                  Hemisphere  = c("North", "South", "All"))
    out$summary$sections$season <- out[["season"]]$summary$All$analyzed
  }
  
   ### --- 6. Model of age-specific reproductive success
  if ("pattern" %in% RepSect) {
    out[["pattern"]] <- Rep_pattern(
      ReproData = subfert,
      ParentPerc = ParentPerc,
      MinN = MinNRepro,
      MinNParents = MinNPaRepro,
      NMinEvenperAge =  NMinEvenperAge
    )
    out$summary$sections$pattern <- out[["pattern"]]$summary$analyzed
  }
  
  
  ### --- 7. Weight at sexual maturity (logistic model)
  if ("weight1st" %in% RepSect && !is.null(GrowthData)) {
    out[["weight1st"]] <- Rep_weight1strepro(
      AnimalData = core,
      parent = parent,
      GrowthData = GrowthData,
      UncertBirth = UncertBirth,
      MinNInd = MinNPaRepro,
      MinNImm = MinNImm,
      MinNMeasures = MinNRepro,
      ParentPerc = ParentPerc,
      Taxa = Taxa,
      maxweight = maxweight,
      MinDate = MinDate
    )
    out$summary$sections$weight1st <- out[["weight1st"]]$summary$analyzed
  }
  
 
  ### --- 8. LRS
  if ("LRS" %in% RepSect ) {
    if(!is.null(lx) && !is.null(mx)){

    out[["LRS"]] <- Rep_LRS(
      ReproData = subfert,
      AnimalData = coresubset,
      lx = lx,
      mx = mx,
      ParentPerc = ParentPerc,
      MinN = MinNPaRepro
    )
    out$summary$sections$LRS <- out[["LRS"]]$summary$analyzed
    }else{
      out$summary$sections$LRS <- FALSE
      out[["LRS"]]$summary$erros = "no lx or mx"
    }
  }
  
  out$summary$analyzed <- TRUE
  return(out)
}
