# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Estimate Interbirth Intervals
#'
#' Computes interbirth intervals (IBIs) for each female based on consecutive offspring birth dates.
#' The function filters records by minimum parentage probability and parent type ("Dam"),
#' computes the time between births, and returns a data frame of intervals, a summary table,
#' and descriptive statistics (mean, median, standard deviation).
#'
#' @param ReproData \code{data.frame}. A dataset containing at least the following columns:
#' \itemize{
#'   \item \code{ParentAnonID}: anonymized ID of the mother
#'   \item \code{Offspring_BirthDate}: birth date of the offspring (must be class \code{Date})
#'   \item \code{Probability}: parentage probability (numeric)
#'   \item \code{ParentType}: must contain values including \code{"Dam"}
#' }
#' @param IntervalIn \code{character}. Unit of time for the interval output.
#' Must be one of: \code{"day"}, \code{"week"}, \code{"month"}, or \code{"year"}.
#' Default is \code{"year"}.
#' @param ParentPerc \code{numeric}. Minimum parentage probability (in %) required to include a mother in the analysis. Default is \code{80}.
#' @param MinNInterval \code{numeric}. Minimum number of intervals required to compute summary statistics.
#' If fewer intervals are available, only the raw data frame will be returned, and an error message will be included. Default is \code{10}.
#' @param NDay \code{numeric}. Minimum number of days between consecutive births required to count as a true interbirth interval (e.g., to avoid counting within-litter spacing). Default is \code{7}.
#'
#' @return A named \code{list} with the following components:
#' \describe{
#'   \item{\code{intervals_df}}{A data frame with one row per interbirth interval, containing:
#'     \code{ParentAnonID}, \code{Offspring_BirthDate}, \code{next_birth}, \code{interval_days}, \code{interval}.}
#'   \item{\code{interval_tab}}{A summary table of rounded interval values (e.g., in years), with frequency and proportion. \code{NULL} if insufficient data.}
#'   \item{\code{summary}}{A list of summary statistics including:
#'     \describe{
#'       \item{\code{NFemales}}{Number of unique mothers with valid intervals}
#'       \item{\code{NInterval}}{Number of valid interbirth intervals}
#'       \item{\code{MeanInterval}}{Mean interbirth interval (in selected unit)}
#'       \item{\code{MedianInterval}}{Median interbirth interval}
#'       \item{\code{SdInterval}}{Standard deviation of intervals}
#'       \item{\code{error}}{Error message if applicable (e.g., not enough data)}
#'     }}
#' }
#'
#' @importFrom dplyr filter arrange group_by mutate ungroup lead n_distinct count
#' @importFrom glue glue
#' @importFrom stats quantile median sd
#' 
#' @export
#' @examples
#' # Example with simulated data
#' df <- data.frame(
#'   ParentAnonID = rep("F1", 4),
#'   Offspring_BirthDate = as.Date(c("2010-01-01", "2011-01-10",
#'                                   "2012-02-15", "2013-03-01")),
#'   Probability = c(80, 80, 90, 100),
#'   ParentType = rep("Dam", 4)
#' )
#' Rep_birthinterval(df, MinNInterval = 2)
#'
#' #Example with ZIMS data
#' data(toy_core)
#' data(toy_collection)
#' data(toy_parent)
#'
#'
#' #prepare Data
#' Data <- Rep_prepdata (coresubset = toy_core, offspring = toy_core, toy_collection, toy_parent,
#'                       MinNRepro = 1, MinNPaRepro = 1,
#'                       BirthType_parent = "All",
#'                       BirthType_offspring = "All" )
#'
#' #Estimate litter size
#' Rep_birthinterval(Data$ReproData)
Rep_birthinterval <- function(ReproData, IntervalIn = "year", ParentPerc = 80, 
                              MinNInterval = 10, NDay = 7) {
  
  # Checks----------------------------------------------------------------------
  assert_that(is.data.frame(ReproData))
  assert_that(ReproData %has_name% c("ParentAnonID", "Offspring_BirthDate", "Probability", "ParentType"))
  assert_that(is.numeric(MinNInterval), is.numeric(ParentPerc), is.numeric(NDay))
  assert_that(IntervalIn %in% c("day", "week", "month", "year"))
  
  NroundDay <- c(day = 1, week = 7, month = 30.5, year = 365.25)[[IntervalIn]]
  # Output initialization ----------------------------------------------------------
  intervals_df <- tibble()
  interval_tab <- NULL
  out_summary <- list(NFemales = 0, NInterval = 0,
                      MeanInterval = NA, MedianInterval = NA, SdInterval = NA,
                      analyzed = FALSE,
                      error = "")
  
  # Filter and compute intervals --------------------------------------------
  intervals_df <- ReproData %>%
    filter(Probability >= ParentPerc,
           #ParentType == "Parentage_Dam"
           ) %>%
    arrange(ParentAnonID, Offspring_BirthDate) %>%
    group_by(ParentAnonID) %>%
    mutate(
      next_birth = lead(Offspring_BirthDate),
      interval_days = as.numeric(difftime(next_birth, Offspring_BirthDate, units = "days")),
      interval = interval_days / NroundDay) %>%
    filter(!is.na(interval), interval > (NDay/NroundDay)) %>%
    ungroup()
  
  if (nrow(intervals_df) >= MinNInterval) {
    interval_tab <- intervals_df %>%
      mutate(interval_rounded = round(interval)) %>%
      count(interval_rounded, name = "N") %>%
      mutate(prop = N / sum(N))
    
    out_summary <- list(
      NParents = n_distinct(intervals_df$ParentAnonID),
      NInterval = nrow(intervals_df),
      MeanInterval = mean(intervals_df$interval_days),
      MedianInterval = median(intervals_df$interval_days),
      SdInterval = sd(intervals_df$interval_days),
      error = "",
      analyzed = TRUE
    )
  } else {
    out_summary$error <- glue("Not enough intervals (n = {nrow(intervals_df)}; min = {MinNInterval})")
  }
  
  return(list(
    intervals_df = intervals_df,
    interval_tab = interval_tab,
    summary = out_summary
  ))
}
