# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Estimate Size at Sexual Maturity
#' 
#' Estimates the relationship between body mass and maturity status based on reproductive data and weight measurements.
#' Uses a mixed-effects logistic regression to estimate the probability of being sexually mature as a function of body mass.
#' Maturity status is determined by comparing measurement dates to the earliest inferred reproduction date.
#'
#' @param AnimalData A \code{data.frame} with individual-level metadata including:
#' \code{AnimalAnonID}, \code{BirthDate}, \code{BirthObserved}, and \code{BirthDateEstimateType}.
#' @param parent A \code{data.frame} of parentage assignments including:
#' \code{ParentAnonID}, \code{AnimalAnonID}, and \code{Probability}.
#' @param GrowthData A \code{data.frame} of weight measurements including:
#' \code{AnimalAnonID}, \code{MeasurementDate}, \code{MeasurementValue}, \code{MeasurementType},\code{MeasurementDateEstimateEnd}, \code{MeasurementDateEstimateStart} and \code{RecordType}.
#' @param UncertBirth Numeric. Maximum tolerated uncertainty in measurement dates (in days; default = 365).
#' @param MinNInd Numeric. Minimum number of unique individuals required (default = 30).
#' @param MinNImm Numeric. Minimum proportion of immature and mature individuals required (default = 0.2).
#' @param MinNMeasures Numeric. Minimum total number of valid weight measures required (default = 50).
#' @param ParentPerc Numeric. Minimum parentage probability to include (default = 80).
#' @param maxweight \code{numeric} the maximum weight allowed for the dataset
#' @param Taxa  \code{character} name of the taxa studied
#' @param MinDate \code{character 'YYYY-MM-DD'} Earliest date to include data
#'
#' @return A list with two elements:
#' \describe{
#'   \item{\code{summary}}{A named list including:
#'     \itemize{
#'       \item \code{Sizeat2.5}, \code{Sizeat50}, \code{Sizeat97.5}: Body mass at which 2.5%, 50%, and 97.5% of individuals are predicted to be mature.
#'       \item \code{Nmeasures}, \code{NMat}, \code{NImm}, \code{NIndividuals}: Sample sizes.
#'       \item \code{analyzed}: Logical, TRUE if analysis was successfully conducted.
#'       \item \code{error}: Message describing why analysis failed (if applicable).
#'     }}
#'   \item{\code{model}}{The fitted \code{glmer} binomial model.}
#' }
#'
#' @importFrom assertthat assert_that
#' @importFrom dplyr filter mutate left_join group_by summarise rename n_distinct select
#' @importFrom lubridate as_date
#' @importFrom glue glue
#' @importFrom lme4 glmer fixef
#' @importFrom stats predict model.matrix plogis poisson vcov
#' @importFrom utils data
#' @importFrom ggplot2 scale_size_continuous scale_y_continuous theme theme_classic   element_text geom_line geom_point geom_ribbon ggplot labs aes
#' @export
#' @examples
#' AnimalData <- data.frame(
#'   AnimalAnonID = 1:100,
#'   BirthDate = as.Date("2010-01-01") + sample(1:5000, 100),
#'   BirthObserved = rep("YES", 100),
#'   BirthDateEstimateType = rep("Exact", 100),
#'   DepartDate = as.Date("2025-01-01"),
#'   SexType = sample(c("M", "F"), 100, replace = TRUE),
#'   BirthUncertainty = 0
#' )
#' parent <- data.frame(
#'   ParentAnonID = sample(1:100, 200, replace = TRUE),
#'   AnimalAnonID = sample(1:100, 200, replace = TRUE),
#'   Probability = sample(c(80, 90, 100), 200, replace = TRUE),
#'   ParentCollectionScopeType = "Global",
#'   OffspringCollectionScopeType = "Global",
#'   ParentOriginType = "Captive"
#' )
#' GrowthData <- data.frame(
#'   AnimalAnonID = sample(1:100, 500, replace = TRUE),
#'   MeasurementDate = as.Date("2013-01-01") + sample(100:3000, 500, replace = TRUE),
#'  MeasurementDateEstimateStart = rep(as.Date("2014-12-01"),500),
#'   MeasurementDateEstimateEnd = rep(as.Date("2015-02-01"), 500),
#' MeasurementType = "Live weight",
#'   MeasurementValue = c(runif(250, 5, 20), runif(250, 30, 80)), # 50% jeunes, 50% matures
#'   EstimatedMeasurement = 0,
#'   RecordType = ""
#' )
#'
#' result <- Rep_weight1strepro(
#'   AnimalData = AnimalData,
#'   parent = parent,
#'   GrowthData = GrowthData,
#'   MinNInd = 20,
#'   MinNImm = 0.2,
#'   MinNMeasures = 50,
#'   ParentPerc = 80,
#'   UncertBirth = 15,
#'   Taxa = "Reptilia"
#' )
#' print(result$summary)
Rep_weight1strepro <- function(AnimalData, parent, GrowthData,
                               UncertBirth = 365,
                               MinNInd = 30, MinNImm = 0.2, MinNMeasures = 50, 
                               ParentPerc = 80, maxweight = NULL, Taxa, MinDate = "1980-01-01") {
  # Checks ----------------------------------------------------------------------
   assert_that(is.data.frame(AnimalData), is.data.frame(parent), is.data.frame(GrowthData))
  assert_that(AnimalData %has_name% c("AnimalAnonID", "BirthDate", "BirthObserved", "BirthDateEstimateType", "BirthUncertainty"))
  assert_that(parent %has_name% c("ParentAnonID", "AnimalAnonID", "Probability"))
  assert_that(GrowthData %has_name% c("AnimalAnonID", "MeasurementDate", "MeasurementValue", "MeasurementType", "RecordType", "MeasurementDateEstimateEnd", "MeasurementDateEstimateStart"))
  assert_that(is.numeric(MinNInd), is.numeric(MinNImm),
              is.numeric(MinNMeasures), is.numeric(UncertBirth))

  
 
  # Initialize outputs ----------------------------------------------------------
  summary <- list(
    Sizeat50 = NA, Sizeat2.5 = NA, Sizeat97.5 = NA,
    Nmeasures = 0, NMat = 0, NImm = 0, NIndividuals = 0,
    analyzed = FALSE, error = ""
  )
  
  if (is.null(maxweight)) { #nocov
   assert_that(Taxa %in% c("Mammalia", "Aves", "Reptilia", "Amphibia", 
   "Chondrichthyes", "Osteichthyes"))
    maxweight <- switch(Taxa,
                        "Mammalia" = 7000,
                        "Aves" = 200,
                        "Reptilia" = 1500,
                        "Amphibia" = 100,
                        "Chondrichthyes" = 1000,
                        "Osteichthyes" = 500)
}
 
      # Clean growth data --------------------------------------------------
  GrowthData <- GrowthData%>%
    mutate(MeasurementDate = lubridate::as_date(MeasurementDate),
           MeasurementDateEstimateStart = lubridate::as_date(MeasurementDateEstimateStart),
           MeasurementDateEstimateEnd = lubridate::as_date(MeasurementDateEstimateEnd),
           Date_Uncert = MeasurementDateEstimateEnd - MeasurementDateEstimateStart)%>%
    filter(MeasurementType == "Live weight",
           MeasurementDate >= MinDate,
           !is.na(MeasurementValue),
           MeasurementValue > 0,
           MeasurementValue < maxweight,
           RecordType == "")
  
  # Remove outliers
  v = Gro_Rout_quan(z =  GrowthData$MeasurementValue, x =  rep(1, nrow( GrowthData)),  
                    minq = 0.05, type = "upper")
  GrowthData =  GrowthData[v==1,]

  
  # Parentage: get first year of reproduction---------------------------------
  subpar <- parent %>%
    filter(Probability >= ParentPerc) %>%
    left_join(AnimalData %>% 
                filter((BirthUncertainty <= UncertBirth)%>% replace_na(TRUE),
                       !(BirthDateEstimateType %in% c('Undetermined', "Indeterminate"))) %>%
                select(AnimalAnonID, BirthDate),
              by = "AnimalAnonID") %>%
    group_by(ParentAnonID) %>%
    summarise(Yearmat = if (all(is.na(BirthDate))) as.Date(NA) else min(BirthDate, na.rm = TRUE),
              .groups = "drop") %>%
    rename(AnimalAnonID = ParentAnonID)
  
  
        # Clean growth data --------------------------------------------------
  GrowthData <- GrowthData%>%
filter(AnimalAnonID  %in% AnimalData$AnimalAnonID,
    (is.na(Date_Uncert) | Date_Uncert <= UncertBirth))

  if (length(GrowthData) == 0) {
    summary$error <- glue("No valid growth data after filtering")
    return(summary)
  }

  
  # Join to determine maturity status ------------------------------------
  TsizeMat <- GrowthData  %>%
    left_join(subpar, by = "AnimalAnonID")%>%
    left_join(AnimalData%>%
                filter(BirthObserved == "YES")%>%select(AnimalAnonID, BirthDate),
              by = "AnimalAnonID")%>%
    mutate(
      Firstyear = coalesce(BirthDate, Yearmat),
      maturity = as.integer(as_date(MeasurementDate) >= as_date(Yearmat))
    ) %>%
    tidyr::drop_na(Firstyear, MeasurementValue)
  
  summary$Nmeasures <- nrow(TsizeMat)
  summary$NMat <- sum(TsizeMat$maturity == 1, na.rm = TRUE)
  summary$NImm <- sum(TsizeMat$maturity == 0, na.rm = TRUE)
  summary$NIndividuals <- dplyr::n_distinct(TsizeMat$AnimalAnonID)
  summary$MeanWeight <- mean(TsizeMat$MeasurementValue)
 summary$SDWeight <- sd(TsizeMat$MeasurementValue)
  
  TsizeMat <-  TsizeMat %>%
    mutate(MeasureSD = (MeasurementValue -summary$MeanWeight)/ summary$SDWeight )%>%
    tidyr::drop_na(maturity)
 
  # --- Check thresholds
  if (summary$Nmeasures < MinNMeasures) {
    summary$error <- glue("Not enough measures (n = {summary$Nmeasures}; min = {MinNMeasures})")
    return(list(summary = summary))
  }
  if ((summary$NImm / summary$NIndividuals) < MinNImm) {
    summary$error <- glue("Not enough immature individuals (prop = {round(summary$NImm / summary$NIndividuals, 2)}; min = {MinNImm})")
    return(list(summary = summary))
  }
  if ((summary$NMat / summary$NIndividuals) < MinNImm) {
    summary$error <- glue("Not enough mature individuals (prop = {round(summary$NMat / summary$NIndividuals, 2)}; min = {MinNImm})")
    return(list(summary = summary))
  }
  if (summary$NIndividuals < MinNInd) {
    summary$error <- glue("Not enough unique individuals (n = {summary$NIndividuals}; min = {MinNInd})")
    return(list(summary = summary))
  }
  
  # Fit maturity model -----------------------------------------------------
  mod = glmer(maturity~MeasureSD + (1|AnimalAnonID), 
              family = "binomial", data = TsizeMat)
  summary$analyzed = TRUE
  # Check p-value of weight effect
  coef_pval <- summary(mod)$coefficients["MeasureSD", "Pr(>|z|)"]
  if (is.na(coef_pval) || coef_pval > 0.05) {
    summary$error= "No signifcant effect of body mass on sexual maturity"
    return(list(summary = summary, model = mod, p = NULL))
  }
  # Estimate weights at 2.5%, 50%, 97.5% maturity    
  seq_weight = seq(0,max(TsizeMat$MeasureSD), 0.01)
  preds <- predict(mod, newdata = tibble::tibble(MeasureSD = seq_weight, AnimalAnonID = 1),
                   re.form = NA, type = "response")
  summary$Sizeat2.5 <- seq_weight[which.min(abs(preds - 0.025))]
  summary$Sizeat50 <- seq_weight[which.min(abs(preds - 0.5))]
  summary$Sizeat97.5 <- seq_weight[which.min(abs(preds - 0.975))]
  
  n_bins <- 10
breaks <- seq(
 0,
  quantile(TsizeMat$MeasurementValue, 0.975,na.rm = TRUE),
  length.out = n_bins + 1
)
bin_dat <- TsizeMat %>%
  mutate(
    bin_id = findInterval(MeasurementValue, breaks, all.inside = TRUE),
    bin_low = breaks[bin_id],
    bin_high = breaks[bin_id + 1],
    bin_mid = (bin_low + bin_high) / 2
  ) %>%
  group_by(bin_id, bin_low, bin_high, bin_mid) %>%
  summarise(
    N = n(),
    n_mature = sum(maturity),
    prop_mature = mean(maturity),
    .groups = "drop"
  ) 
# Relationship between unstandardized and standardized measurement
pred_dat <- data.frame(
  MeasurementValue = seq(
   0,
  quantile(TsizeMat$MeasurementValue, 0.975,na.rm = TRUE),
    length.out = 300
  )
)
pred_dat$MeasureSD <-(pred_dat$MeasurementValue -summary$MeanWeight)/ summary$SDWeight
pred_dat2 = predict(mod, newdata = pred_dat, type = "link", re.form = NA, se.fit = TRUE)
pred_dat <- pred_dat %>%
  mutate(
    fit = plogis(pred_dat2$fit),
    lwr = plogis(pred_dat2$fit - 1.96 * pred_dat2$se.fit),
    upr = plogis(pred_dat2$fit + 1.96 * pred_dat2$se.fit)
  )

  p = ggplot() +

  # Model confidence ribbon
  geom_ribbon(
    data = pred_dat,
    aes(x = MeasurementValue, ymin = lwr, ymax = upr),
    fill = "#E31A1C",
    alpha = 0.18
  ) +

  # Model prediction line
  geom_line(
    data = pred_dat,
    aes(x = MeasurementValue, y = fit),
    color = "#E31A1C",
    linewidth = 1.2
  ) +
  # Observed percentage points
  geom_point(
    data = bin_dat,
    aes(x = bin_mid, y = prop_mature, size = N),
    shape = 21,
    fill = "white",
    color = "black",
    stroke = 0.8
  ) +
  scale_y_continuous(
    labels = scales::percent_format(accuracy = 1),
    limits = c(-0.05, 1.08),
    breaks = seq(0, 1, 0.25)
  ) +
  scale_size_continuous(
    range = c(2.5, 6),
    guide = "none"
  ) +

  labs(
    x = "Body Mass",
    y = "Sexual Maturity",
    ) +

  theme_classic(base_size = 14) +
  theme(
      axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black"),
    legend.position = "none"
  )
  
  return(list(summary = summary, model = mod, p =p))
}

