# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Litter Size Estimation
#'
#' Creates a data frame of litter size per mother and birth date, and generates summary tables of litter size statistics. 
#' Only offspring-mother associations with sufficient parentage probability are included.
#'
#' @param ReproData \code{data.frame}. A dataset including at least the following columns: 
#' \emph{AnimalAnonID}, \emph{ParentAnonID}, \emph{ParentType}, \emph{Probability}, 
#' \emph{Offspring_BirthDate}, \emph{Offspring_Inst}, and \emph{ParentAge}.
#' @param NDay \code{numeric}. Maximum number of consecutive days within which offspring are considered to belong to the same litter or clutch (default is 7).
#' @param ParentPercDam \code{numeric}. Minimum parentage probability (in %) required to include a Dam (default is 80).
#' @param ParentPercSire \code{numeric}. Minimum parentage probability (in %) required to include a Sire (default is 80).
#' @param MinNLitter \code{numeric}. Minimum number of litters required to compute summary statistics. The detailed litter data frame will be returned in all cases (default is 30).
#'
#' @return A list with the following components:
#' \item{summary}{A named list with litter size statistics:
#'   \describe{
#'     \item{NOffsp_prob}{Number of offspring with qualifying parentage probability}
#'     \item{NParent_prob}{Number of dams (mothers) with qualifying parentage probability}
#'     \item{NReprEvent}{Total number of reproductive events (litters)}
#'     \item{MeanLittSize}{Mean litter size}
#'     \item{MedLittSize}{Median litter size}
#'     \item{SELittSize}{Standard error of litter size}
#'     \item{analyzed}{Logical. Whether summary statistics could be calculated (TRUE) or not (FALSE)}
#'     \item{error}{Character string explaining why summary stats were not calculated, if applicable}
#'     \item{Nerr}{Error code: 0 = no error, 4 = no births meet criteria, 5 = not enough litters}
#'   }}
#' \item{littSizeDf}{A data frame with one row per litter, including litter size and associated parental information.}
#' \item{littSizeTab}{A table of litter sizes: frequency and proportion for each size.}
#' \item{littSizeperAge}{A data frame showing mean and standard deviation of litter size by maternal age.}
#'
#' @export
#'
#' @examples
#' data(toy_core)
#' data(toy_collection)
#' data(toy_parent)
#'
#'
#' #prepare Data
#' Data <- Rep_prepdata (coresubset = toy_core, offspring = toy_core, toy_collection, toy_parent, 
#'                       MinNRepro = 1, MinNPaRepro = 1,
#'                       BirthType_parent = "All",
#'                       BirthType_offspring = "All" )
#'
#' #Estimate litter size
#' out <- Rep_littersize(Data$ReproData, MinNLitter = 5,
#'                       NDay = 7)
#' print(out$summary)
Rep_littersize <- function(ReproData,
                           NDay = 7, 
                           ParentPercDam = 80,
                           ParentPercSire = 80,
                           MinNLitter = 30) {
  # Checks----------------------------------------------------------------------
  assert_that(is.data.frame(ReproData))
  assert_that(ReproData %has_name% c("AnimalAnonID", "ParentAnonID", "Probability", 
                                     "ParentType", "Offspring_BirthDate",
                                     "Offspring_Inst", "ParentAge"))
  assert_that(is.numeric(NDay), is.numeric(ParentPercDam),
              is.numeric(ParentPercSire), is.numeric(MinNLitter))
  
  # Output initialization ----------------------------------------------------------
  littSumm <- list(NOffsp_prob = NULL, NParent_prob = NULL, NReprEvent = NULL,
                   analyzed = FALSE, error = "", Nerr= 0,
                   MeanLittSize = NULL, MedLittSize = NULL, SELittSize = NULL, 
                   MinLittSize = NULL, MaxLittSize = NULL)
  littSizeDf <- tibble()
  littSizeTab <- NULL
  littSizeperAge <- NULL
  
  # Filter sires
  subpar_sire <- ReproData %>%
    filter(ParentType == "Parentage_Sire",
           Probability >= ParentPercSire) %>%
    transmute(FatherAnonID = ParentAnonID,
              AnimalAnonID,
              Father_Age = round(ParentAge, 1)) %>%
    distinct()
  
  # Filter dams and join sires
  subpar <- ReproData %>%
    filter(ParentType == "Parentage_Dam",
           Probability >= ParentPercDam) %>%
    left_join(subpar_sire, by = "AnimalAnonID") %>%
    select(ParentAnonID, AnimalAnonID, Offspring_BirthDate,
           Offspring_Inst, FatherAnonID, Father_Age, ParentAge) %>%
    distinct()
  
  littSumm$NOffsp_prob <- n_distinct(subpar$AnimalAnonID)
  littSumm$NParent_prob <- n_distinct(subpar$ParentAnonID)
  
  if(nrow(subpar) >0){
    
    # Nest by mother
    nested <- subpar %>%
      mutate(Mother_Age = round(ParentAge, 2)) %>%
      group_by(ParentAnonID) %>%
      arrange(Offspring_BirthDate, .by_group = TRUE) %>%
      tidyr::nest()
    
    # Apply litter detection per mother
    nested <- nested %>%
      mutate(data = purrr::map(data, ~ {
        df <- .x
        diff <- c(NDay + 1, diff(as.numeric(df$Offspring_BirthDate)))
        df$litter <- cumsum(diff > NDay)
        df
      })) %>%
      tidyr::unnest(cols = c(data)) %>%
      group_by(ParentAnonID, Offspring_Inst, litter, Mother_Age) %>%
      summarise(
        litterSize = n_distinct(AnimalAnonID),
        MeanBirthDate = median(Offspring_BirthDate),
        OffspringAnonID = list(unique(AnimalAnonID)),
        FatherAnonID = list(unique(FatherAnonID)),
        Father_Age = list(unique(Father_Age)),
        .groups = "drop"
      ) %>%
      rename(MotherAnonID = ParentAnonID,
             InstitutionAnonID = Offspring_Inst)
    
    # Unnest again and regroup
    littSizeDf <- nested %>%
      tidyr::unnest(cols = c(FatherAnonID, Father_Age)) %>%
      distinct() %>%
      group_by(MotherAnonID, InstitutionAnonID, litterSize, MeanBirthDate, Mother_Age) %>%
      summarise(
        OffspringAnonID = list(unique(OffspringAnonID)),
        FatherAnonID = list(unique(FatherAnonID)),
        Father_Age = list(unique(Father_Age)),
        .groups = "drop"
      )
    
    # Compute summaries
    if (nrow(littSizeDf)>= MinNLitter)  {
      littSizeTab <- littSizeDf %>%
        dplyr::count(litterSize, name = "N") %>%
        mutate(prop = N / sum(N))
      
      
      littSizeperAge <- littSizeDf%>%
        mutate(Mother_Age = floor(Mother_Age))%>%
        group_by(Mother_Age)%>%
        summarise(MeanlittSize = mean(litterSize),
                  SDlittSize = ifelse(nrow(cur_group())==1,0, sd(litterSize, na.rm = TRUE)),
                  SElittSize =  SDlittSize/sqrt(n()),
                  Nlitter = n(),
                  .groups = 'drop')%>%
        ungroup()
      
      # Summary
      littSumm$MeanLittSize =  mean(littSizeDf$litterSize)
      littSumm$MedLittSize = median(littSizeDf$litterSize)
      littSumm$SELittSize = sd(littSizeDf$litterSize)/sqrt(nrow(littSizeDf))
      littSumm$MinLittSize =  min(littSizeDf$litterSize)
      littSumm$MaxLittSize =  max(littSizeDf$litterSize)
      littSumm$analyzed = TRUE 
      littSumm$NReprEvent= sum(littSizeTab$N)
    }else{
      littSumm$error = glue::glue("{nrow(littSizeDf)} litters < {MinNLitter}")
      littSumm$Nerr = 5
    }
  }else{
    littSumm$error = glue::glue("No births with parentage probability higher than {ParentPercDam}") #nocov
    littSumm$Nerr = 4 #nocov
    
  }
  return(list(summary = littSumm, 
              littSizeDf = littSizeDf,  
              littSizeTab =  littSizeTab,
              littSizeperAge = littSizeperAge))
}
