# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Prepare Reproduction Data
#' 
#' Prepares harmonized reproduction data for analyses, including offspring sex and birth date, 
#' parent age at offspring birth, and data on potential reproductive individuals at each age. 
#' Filters records based on birth type, collection scope, and minimum data availability thresholds.
#'
#' @param coresubset \code{data.frame}. Cleaned core data with selected individuals and valid birth dates. 
#' Must include columns: \emph{AnimalAnonID}, \emph{BirthType}, \emph{MaxBirthDate}, 
#' \emph{MinBirthDate}, \emph{DepartDate}, \emph{BirthDate}, \emph{SexType}, 
#' \emph{FirstHoldingInstitution}, \emph{GlobalStatus}.
#' @param offspring A \code{data.frame} of individual-level records including offspring. Must include columns: \code{AnimalAnonID}, \code{BirthType}, \code{MaxBirthDate}, \code{MinBirthDate}, \code{DepartDate}, \code{BirthDate}, \code{SexType}, \code{FirstHoldingInstitution}, and \code{GlobalStatus}.
#' @param collection \code{data.frame}. Collection data with columns: 
#' \emph{AnimalAnonID}, \emph{ScopeType}, \emph{ChangeDate}.
#' @param parent \code{data.frame}. Parentage information with columns: 
#' \emph{ParentAnonID}, \emph{ParentCollectionScopeType}, \emph{OffspringCollectionScopeType}, 
#' \emph{AnimalAnonID}, \emph{ParentOriginType}, \emph{Probability}.
#' @param contraception \code{data.frame}. Contraception records including columns: 
#' \emph{AnimalAnonID}, \emph{Date}, \emph{Status}. (default: \code{NULL}).
#' @param BirthType_parent \code{character}. Either \code{"Captive"}, \code{"Wild"}, or \code{"All"}. 
#' Filter for candidate reproductive adults (default: \code{"Captive"}).
#' @param BirthType_offspring \code{character}. Either \code{"Captive"}, \code{"Wild"}, or \code{"All"}. 
#' Filter for offspring used in reproductive analyses (default: \code{"Captive"}).
#' @param Global \code{logical}. If \code{TRUE}, restricts to global collection scope for parents and offspring (default: \code{TRUE}).
#' @param MinNRepro \code{numeric}. Minimum number of births required to proceed with analysis (default: \code{50}).
#' @param MinDate \code{date} Earliest offspring birth date to include data
#' @param MinNPaRepro \code{numeric}. Minimum number of unique parents with known age required to proceed (default: \code{30}).
#' @param RemContra \code{logical}. Whether contraception data should be used to remove individuals under contraception (see details) (default: \code{FALSE}).
#' 
#' @details
#' Contraception: An individual is removed for the rolling year around the dates when it is recorded under Active Contraception.
#'
#' @return A named \code{list} with:
#' \describe{
#'   \item{\code{ReproData}}{A data.frame of parent-offspring pairs, including parent age at birth and offspring info.}
#'   \item{\code{Adults}}{A data.frame of candidate reproductive adults, expanded by age.}
#'   \item{\code{summary}}{A tibble with the following metrics: 
#'     \itemize{
#'       \item \code{Nbirths}: Total number of offspring birth records.
#'       \item \code{Nadults}: Total number of candidate reproductive adults.
#'       \item \code{NPar_core}: Number of parents from core data.
#'       \item \code{NPar_off_core}: Number of parent entries matched to valid offspring.
#'       \item \code{NOffsp}: Number of valid offspring matched.
#'       \item \code{NParent}: Number of unique parent IDs with offspring.
#'       \item \code{NOffsp_age}: Offspring with known parent age > 0.
#'       \item \code{NParent_age}: Unique parents with known age > 0 and valid offspring.
#'       \item \code{NInst}: Number of institutions represented.
#'       \item \code{analyzed}: \code{TRUE} if thresholds are met.
#'       \item \code{err}: Error message (if analysis cannot proceed).
#'       \item \code{Nerr}: Numeric code for error type (0 = none, 1 = insufficient births, 2 = insufficient parents).
#'     }
#'   }
#' }
#'
#'
#' @importFrom dplyr filter mutate select rename left_join group_by summarise distinct ungroup n_distinct
#' @importFrom tidyr uncount
#' @importFrom assertthat assert_that
#' @export
#'
#' @examples
#' data(toy_core)
#' data(toy_collection)
#' data(toy_parent)
#'
#' Data <- Rep_prepdata (coresubset = toy_core, offspring = toy_core, toy_collection, toy_parent,
#'                       BirthType_parent = "Captive", BirthType_offspring = "Captive"
#' )
Rep_prepdata <- function(coresubset,offspring, collection, parent, contraception = NULL,
                         MinNRepro=50, MinNPaRepro =30,
                         BirthType_parent = "Captive", BirthType_offspring = "Captive", 
                         MinDate = as_date("1980-01-01"),
                         Global = TRUE, RemContra = FALSE
) {
  # Check correct format for inputs ------------------------------------------ 
  assert_that(is.data.frame(coresubset))
  assert_that(is.data.frame(offspring))
  assert_that(is.data.frame(collection))
  assert_that(is.data.frame(parent))
  assert_that(coresubset %has_name% c("AnimalAnonID", 'BirthType', "MaxBirthDate", 
                                      "MinBirthDate", "DepartDate", "BirthDate",
                                      "SexType", "FirstHoldingInstitution", "GlobalStatus"))
  assert_that(offspring %has_name% c("AnimalAnonID", 'BirthType', "MaxBirthDate", 
                                      "MinBirthDate", "DepartDate", "BirthDate",
                                      "SexType", "FirstHoldingInstitution", "GlobalStatus"))
  assert_that(collection %has_name% c("AnimalAnonID", "ScopeType", "ChangeDate"))
  assert_that(parent %has_name% c("ParentAnonID", "ParentCollectionScopeType", 
                                  "OffspringCollectionScopeType", "AnimalAnonID",
                                  "ParentOriginType", "Probability"))
  assert_that(is.character(BirthType_parent))
  assert_that(BirthType_parent %in% c("Captive", "Wild", "All"))
  assert_that(is.character( BirthType_offspring))
  assert_that( BirthType_offspring %in% c("Captive", "Wild", "All"))
  assert_that(is.logical(Global))
  assert_that(is.logical(RemContra))
  
  if(RemContra){
   assert_that(is.data.frame(contraception))
  assert_that(contraception %has_name% c("AnimalAnonID", "Date", "Status"))
}
  # Initialize outputs ----------------------------------------------------------
  fertSumm <- tibble(Nbirths = 0,
                     Nadults = 0,
                     NPar_core = 0, NPar_off_core = 0,
                     NOffsp = 0, NParent = 0,
                     NOffsp_age = 0, NParent_age = 0,NInst = 0,
                     analyzed = TRUE, Nerr = 0, err = ""
  )
  
  #Offspring       
  offspring = offspring%>%filter(BirthDate >= MinDate)
 coresubset = coresubset%>%filter(BirthDate >= MinDate)
  if (BirthType_offspring != "All"){
    offspSub <- offspring %>%
      filter(stringr::str_detect(BirthType, pattern = BirthType_offspring))
  }else{offspSub<- offspring}
  # Number of birth records:
  fertSumm$Nbirths <- nrow(offspSub)
  
  
  # Adults:
  if (BirthType_parent != "All"){
    adults <- coresubset %>%
      filter(stringr::str_detect(BirthType, pattern = BirthType_parent))
  }else{adults<- coresubset}
  
  adults <- adults%>%
    # Find Depart ages of all inds in adults table:
    mutate(ageAds = floor(as.numeric(DepartDate - BirthDate) / 365.25))%>%
    #increase the table to have a row per individual and per age
    tidyr::uncount(weights = ageAds, .id = "n", .remove = F) %>%
    mutate(Age = ageAds - n,
           Date_age = BirthDate + lubridate::years(Age))%>%
    distinct()
  
  if(Global & nrow(adults)>0){
    adults <- adults%>%
      filter(AnyLocalCollectionFlag == 0)
    
    parent <- parent %>%
      filter(ParentCollectionScopeType == "Global",
             OffspringCollectionScopeType == "Global")
  }
  
  
  #Remove individuals under contraception
  if(RemContra){
    # Extract contraception method:
    Contra =  contraception%>%filter(
      AnimalAnonID %in% adults$AnimalAnonID,
    Status == "Active")%>%
      mutate(Date = as_date(Date))%>%
      left_join(coresubset %>%select(AnimalAnonID, BirthDate), by = "AnimalAnonID")%>%
       mutate(ageAds = floor(as.numeric(Date - BirthDate) / 365.25))%>%
      distinct()%>%
      select(AnimalAnonID, ageAds, Status)

    # Find which individuals are in the contraception data:
         adults <- adults %>%
              left_join(Contra, by = c("AnimalAnonID","ageAds"))%>%
           filter(is.na(Status))
}
  
  
  
  # Number of adult records:
  fertSumm$Nadults <- length(unique(adults$AnimalAnonID))
  
  
  if ( fertSumm$Nadults > 0) {
    
    #select parents and remove duplicated rows
    subpar <- parent %>%
      filter(ParentAnonID %in% unique(adults$AnimalAnonID))%>% 
      left_join(adults%>%select(AnimalAnonID, BirthDate,DepartDate, BirthType, GlobalStatus)%>%
      rename(Parent_BirthDate = BirthDate,
             Parent_DepartDate = DepartDate,
             Parent_BirthType = BirthType)%>%distinct(),
                relationship = "many-to-many",
                by =c("ParentAnonID" = "AnimalAnonID"))%>% 
      distinct() 
    
    fertSumm$NPar_core <- nrow(subpar)
    subpar <-subpar %>%
      #Offspring not in coresubset
      filter(AnimalAnonID %in% offspSub$AnimalAnonID)%>%
      left_join(offspSub%>%select(AnimalAnonID, BirthDate, SexType, FirstHoldingInstitution),
                by =c("AnimalAnonID" = "AnimalAnonID"))%>%
      rename(Offspring_BirthDate = BirthDate,
             Offspring_Inst = FirstHoldingInstitution)%>%
      mutate(ParentAge = as.numeric(Offspring_BirthDate - 
                                      Parent_BirthDate) / 365.25)
    fertSumm$NPar_off_core <- nrow(subpar)
    
    if(nrow(subpar)>0){
      fertSumm$NInst <- n_distinct(subpar$Offspring_Inst)
      # Number of births
    fertSumm$NOffsp <- length(unique(subpar$AnimalAnonID))
    fertSumm$NParent <- length(unique(subpar$ParentAnonID))
  }
    
    
    
    if (fertSumm$NOffsp   > 0 ) {
      #Keep only repro with age of parents at birth >0 
      subpar <- subpar%>%
        group_by(AnimalAnonID, ParentOriginType, ParentAnonID,  ParentType,
                 OffspringCollectionScopeType, ParentCollectionScopeType, 
                 Parent_BirthDate, Parent_BirthType, Offspring_BirthDate,
                 SexType, ParentAge, Offspring_Inst, GlobalStatus)%>%
        summarise(Probability = max(Probability, na.rm = TRUE))%>%
        filter(ParentAge>0)%>%ungroup()
      
      fertSumm$NOffsp_age <- length(unique(subpar$AnimalAnonID))
      fertSumm$NParent_age <- length(unique(subpar$ParentAnonID))
      
      
    } 
    
  }
  if (fertSumm$NParent_age < MinNPaRepro ) {
    Adults = subpar = tibble()
    fertSumm$analyzed = FALSE
    fertSumm$err = "Nparents < minNparep"
    fertSumm$Nerr = 2
  }
  if (fertSumm$NOffsp_age < MinNRepro ) {
    Adults = subpar = tibble()
    fertSumm$analyzed = FALSE
    fertSumm$err = "Nbirths < MinNRepro"
    fertSumm$Nerr = 1
  }
  
  # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  
  
  return(list(Adults = adults, ReproData = subpar, summary =  fertSumm))
  }
