# WARNING - Generated by {fusen} from dev/flat_repro.Rmd: do not edit by hand # nolint: line_length_linter.

#' Reproductive age pattern estimation
#'
#' This function models reproductive success (number of offspring per age) as a function of age using 0, 1, or 2-threshold Poisson regression models. It selects the best model via AIC, and returns the predicted age(s) of maximum reproductive output.
#'
#' @param ReproData A \code{data.frame} with reproductive events including: \code{AnimalAnonID}, \code{ParentAnonID}, \code{Probability}, and \code{ParentAge}.
#' @param MinN Integer. Minimum number of reproductive events required to perform the analysis. Default: 30.
#' @param MinNParents Integer. Minimum number of unique parents required to perform the analysis. Default: 10.
#' @param NMinEvenperAge Integer. Minimum number of events per age class to include the age class. Default: 3.
#' @param ParentPerc Numeric. Minimum parentage probability to retain a reproductive event. Default: 80.
#'
#' @return A \code{list} with:
#' \describe{
#'   \item{\code{summary}}{A list containing:
#'     \itemize{
#'       \item{\code{analyzed}}: Logical, whether the analysis was performed.
#'       \item{\code{model_type}}: Chosen model type (0 = constant, 1 = one threshold, 2 = two thresholds).
#'       \item{\code{T1}}: First threshold (if applicable).
#'       \item{\code{T2}}: Second threshold (if applicable).
#'       \item{\code{MaxAgeLS}}: Age(s) with highest predicted reproductive output.
#'       \item{\code{Nevents}}: Total number of events.
#'       \item{\code{NparentsP}}: Total number of parents.
#'       \item{\code{error}}: Error message (if applicable).
#'     }
#'   }
#'   \item{\code{model}}{Fitted \code{glm} model object.}
#' }
#'
#' @importFrom dplyr filter mutate group_by summarise rename n_distinct count
#' @importFrom stats glm AIC predict
#' @importFrom assertthat assert_that
#' @export
#' @examples
#' # Simulated data
#' set.seed(42)
#' df <- data.frame(
#'   AnimalAnonID = sample(1:100, 500, replace = TRUE),
#'   ParentAnonID = sample(1:50, 500, replace = TRUE),
#'   Probability = runif(500, 50, 100),
#'   ParentAge = sample(3:20, 500, replace = TRUE)
#' )
#'
#' out <- Rep_pattern(df)
#' print(out$summary)
Rep_pattern <- function(ReproData,
                        MinN = 30, MinNParents = 10, 
                        NMinEvenperAge = 3, ParentPerc=80) {
  # Checks
  assert_that(is.data.frame(ReproData))
  assert_that(ReproData %has_name% c("AnimalAnonID", "ParentAnonID", "Probability", 
                                     "ParentAge"))
  assert_that(is.numeric(MinN), is.numeric(MinNParents),
              is.numeric(NMinEvenperAge), is.numeric(ParentPerc))
  
  data <- ReproData %>%
    filter(Probability >= ParentPerc)%>%
    mutate(ParentAge = round(ParentAge,1))%>%
    group_by(ParentAnonID, ParentAge) %>%
    summarise(LS = dplyr::n_distinct(AnimalAnonID), .groups = "drop") %>%
    rename(Age = ParentAge)
  
  # Initialize summary
  summary <- list(
    analyzed = FALSE,
    model_type = NA,
    T1 = NA,
    T2 = NA,
    MaxAgeLS = NULL,
    error = "",
    Nevents = nrow(data),
    NparentsP = dplyr::n_distinct(data$ParentAnonID)
  )
  
  # Check thresholds
  
  if (summary$Nevents < MinN) {
    summary$error <- glue::glue("Too few reproductive events (n = {summary$Nevents}, min = {MinN})")
    return(list(summary = summary, model = NULL))
  }
  if (summary$Nparents < MinNParents) {
    summary$error <- glue::glue("Too few parents (n = {summary$Nparents}, min = {MinNParents})")
    return(list(summary = summary, model = NULL))
  }
  
  # Prepare thresholds
  age_counts <- data %>% mutate(Age = floor(Age)) %>% count(Age)
  
  if (max(age_counts$n) < NMinEvenperAge) {
    summary$error <- glue::glue("Too few events per Age (n_max = {max(age_counts$n)}, min = {NMinEvenperAge})")
    return(list(summary = summary, model = NULL))
  }
  
  ages <- c(min(age_counts$Age): max(age_counts$Age[age_counts$n>=NMinEvenperAge]))
  nAges <- length(ages)
  
  if (nAges < 3) {
    summary$error <- "Insufficient age classes with minimum data"
    return(list(summary = summary, model = NULL))
  }
  
  AIC_detailed <- tibble::tibble(
    Model = character(),
    T1 = numeric(),
    T2 = numeric(),
    AIC = numeric(),
    k = character()
  )
  
  
  # Constant model
  mod0 <- glm(LS ~ 1, data = data, family = poisson())
  aic0 <- AIC(mod0)
  AIC_detailed <- add_row(AIC_detailed, Model = "Null", T1 = NA, T2 = NA, 
                          AIC = aic0, k = "1")
  preds0 <- rep.int(predict(mod0, type = "response"), length(ages))
  
  # One-threshold model
  best1 <- list(aic = Inf)
  for (T1 in ages) {
    d <- data %>%
      mutate(a1 = ifelse(Age < T1, Age - T1, 0),
             a2 = ifelse(Age > T1, Age - T1, 0))
    mod <- glm(LS ~ a1 + a2, data = d, family = poisson())
    aic_adj <- AIC(mod) + 2
    AIC_detailed <- add_row(AIC_detailed, Model = "1-threshold", 
                            T1 = T1, T2 = NA, AIC = aic_adj, k = "2+1")
    if (aic_adj < best1$aic) {
      preds <- predict(mod, newdata = data.frame(
        Age = ages,
        a1 = ifelse(ages < T1, ages - T1, 0),
        a2 = ifelse(ages > T1, ages - T1, 0)
      ), type = "response")
      best1 <- list(mod = mod, T1 = T1, aic = aic_adj, preds = preds)
    }
  }
  
  # Two-threshold model
   best2 <- list(aic = Inf)
  for (i in 1:(nAges - 1)) {
    for (j in (i + 1):nAges) {
      T1 <- ages[i]
      T2 <- ages[j]
      d <- data %>%
        mutate(a1 = ifelse(Age < T1, Age - T1, 0),
               a2 = ifelse(Age >= T1 & Age <= T2, Age - T1, 0),
               a3 = ifelse(Age > T2, Age - T2, 0))
      mod <- glm(LS ~ a1 + a2 + a3, data = d, family = poisson())
      aic_adj <- AIC(mod) + 4
      AIC_detailed <- add_row(AIC_detailed, Model = "2-threshold",
                              T1 = T1, T2 = T2, AIC = aic_adj, k = "3+2")
      if (aic_adj < best2$aic) {
        preds <- predict(mod, newdata = data.frame(
          Age = ages,
          a1 = ifelse(ages < T1, ages - T1, 0),
          a2 = ifelse(ages >= T1 & ages <= T2, ages - T1, 0),
          a3 = ifelse(ages > T2, ages - T2, 0)
        ), type = "response")
        best2 <- list(mod = mod, T1 = T1, T2 = T2, aic = aic_adj, preds = preds)
      }
    }
  }
  
  # Select best model
  all_aics <- c(aic0, best1$aic, best2$aic)
  model_type <- which.min(all_aics) - 1
  
  final_model <- switch(as.character(model_type),
                        "0" = mod0,
                        "1" = best1$mod,
                        "2" = best2$mod)
  preds <- switch(as.character(model_type),
                  "0" = preds0,
                  "1" = best1$preds,
                  "2" = best2$preds)
MaxAgeLS <- ages[which.max(preds)]
  
  summary$analyzed <- TRUE
  summary$model_type <- model_type
  summary$T1 <- if (model_type == 1) best1$T1 else if (model_type == 2) best2$T1 else NA
  summary$T2 <- if (model_type == 2) best2$T2 else NA
  summary$MaxAgeLS <- MaxAgeLS
  
  return(list(summary = summary, model = final_model, AIC_detailed = AIC_detailed, predictions = preds))
}
