# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create output and plots for the survival analysis
#' 
#'  estimates key metrics from the selected survival model and returns illustrating plots of the survival model.
#'
#' @param out \code{list} output of the survival analysis,  returns from `Sur_ana()`
#' @param MinAge \code{numeric} Age at which the survival analysis should start, in years.  see ?basta for more information.
#' @param MinMLE \code{numeric} Value used for checks. Minimum survivorship allowed at mean life expectancy. Between 0 and 1.
#' @param MaxLE \code{numeric} Value used for checks. Maximum remaining life expectancy at last observed age. In years.
#' @param MinLx  \code{numeric} Value used for longevity threshold and for checks. between 0 and 1. Minimum reached survivorship from the raw Kaplan-Meier analysis. This number avoids running survival analysis if there are too few dead individuals in the data. Lower is better.
#' @param MaxAge \code{numeric} Maximum possible age in years. Only used for model predictions. This argument is not used to select data.
#' @param ncpus  \code{numeric} Number of CPU cores to use. 
#' @param PlotDir \code{character} Directory to save the plots. If \code{NULL}, no plot is saved
#' @param PlotName \code{character} Name used to save the plots.
#' 
#' @return The output list of the survival analysis including, in addition:
#' * Key survival metrics including Mean life expectancy (MLE & Ex), median life
#' expectancy (L50) and  age at which 90% of the individual died (Longevity = L90)
#' estimated from raw data, the Kaplan-Meier estimator, and the survival model. Estimates
#' include ages from birth or from age at sexual maturity (if given). First year
#' survival, First month survival, Entropy (H and Epx = -log(H)), coefficient of
#' variation (CV) and Gini coefficient (G) are also estimated from the Kaplan-Meier
#' estimator and the survival model.
#' * Checks of the fit for the selected survival model:
#'     * Gof_KM_coeff1: Percentage of age points where the KM estimator is outside of the
#'     95% CI of the survivorship estimated from the survival model.
#'     * Gof_KM_coeff2: Maximum sum of same sign residuals between KM estimator and
#'     survival model
#'     * Gof_Martingal_KM: Value of the test that must be compared to a kolmogorov Smirnov table and test telling if the model fits
#'     * LxatMLE: Estimated survivorship at mean life expectancy
#'     * LEmaxOage: Life expectancy at max observed age
#'     * KMMinLx: Minimum survivorship reached by the Kaplan-Meier estimator
#' * The remaining life expectancy per age (relex_from0)
#' * The probability to live 5 years more (Sur5)
#' * Age-specific survival  (Sur1)
#' * Monthly survival  (Sur1m)
#' * Plots if requested
#'     * One showing the convergence of chains, together with estimated survivorship and
#'     survival and mortality rates.
#'     * The second showing remaining life-expectancy, and the age-specific probability
#'     to live 1 year more.
#' @export
#'
#' @importFrom grDevices pdf dev.off
#' @importFrom graphics lines
#'
#' @examples
#' data(toy_core)
#' data(toy_deathinformation)
#' out <- Sur_ana(toy_core,  DeathInformation = toy_deathinformation, 
#'                Models = "GO", Shape = "simple",
#'                niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
#'
#' out <- Sur_out(out, ncpus = 3)
Sur_out <- function(out,
                    MinAge = 0, MinMLE = 0.1, MaxLE = 2, MinLx = 0.1,
                    MaxAge = 120,
                    ncpus = 2, 
                    PlotDir = NULL, PlotName = ''
) {
  # Check correct format for inputs ---------------------------------------------
  assert_that(is.list(out))
  assert_that(out %has_name% c("summary", "metrics", "bastaRes", "DICmods", "bastatab"))
  
  assert_that(!is.null(out$summary))
  assert_that(!is.null(out$metrics))
  assert_that(!is.null(out$bastaRes),
              msg = "out$bastaRes must not be NULL. Sur_out() requires a fitted BaSTA model.")
  assert_that(!is.null(out$bastatab))
  
  assert_that(is.numeric(MinAge))
  assert_that(length(MinAge) == 1)
  assert_that(MinAge >= 0)
  
  assert_that(is.numeric(MaxAge))
  assert_that(length(MaxAge) == 1)
  assert_that(MinAge < MaxAge)
  
  assert_that(is.numeric(MinLx))
  assert_that(length(MinLx) == 1)
  assert_that(MinLx >= 0 && MinLx <= 1)
  
  assert_that(is.numeric(MinMLE))
  assert_that(length(MinMLE) == 1)
  assert_that(MinMLE >= 0 && MinMLE <= 1)
  
  assert_that(is.numeric(MaxLE))
  assert_that(length(MaxLE) == 1)
  
  assert_that(is.numeric(ncpus))
  assert_that(length(ncpus) == 1)
  assert_that(ncpus > 0)
  
  assert_that(is.character(PlotName))
  assert_that(length(PlotName) == 1)
  
  if (!is.null(PlotDir)) {
    checkmate::assert_directory_exists(PlotDir)
  }
  
  # Initialize outputs ----------------------------------------------------------
  out$check <- list(
    Gof_KM_coeff1 = NA_real_,
    Gof_KM_coeff2 = NA_real_,
    LxatMLE = NA_real_,
    LEmaxOage = NA_real_,
    KMMinLx = NA_real_,
    Gof_Martingal_KM = NA_real_,
    Gof_Martingal_test = NA
  )
  
  #Check if model is gompertz report b -----------------------------------------
  if(out$bastaRes$modelSpecs[["model"]] =="GO"){
    out$metrics = rbind(out$metrics,
                        tibble::tibble(Data = 'Model',
                               firstage = MinAge,
                               param = "b_Gomp",
                               stat = c("mean", "sd", "lower", "upper"),
                               value = out$bastaRes$coefficient[2,c(1:4)]
                        ))
  }
  
  # Define maximum predicted age: age at L(x) = 0.005---------------------------
  Lx_mean <- out$bastaRes$surv$nocov[1,]
  idMaxAge <- out$bastaRes$x[which(Lx_mean < 0.005)][1]+MinAge
  if (is.na(idMaxAge)) {
    MaxAge <- min(max(out$bastaRes$x)+MinAge, MaxAge)
  } else {MaxAge = idMaxAge}
  paramax = length(out$bastaRes$names)
  if("lambda" %in% out$bastaRes$names){paramax = paramax-1}
  
  
  # Estimate posterior of Lx from the best survival model-----------------------
  # run parallel estimation:
  dx = 0.01
  xv = seq(MinAge, MaxAge, by = dx)
    sfInit(parallel = TRUE, cpus = ncpus)
  on.exit(sfStop(), add = TRUE)
  Lxparal <- sfClusterApplyLB(1:ncpus, Sur_Lx, theMat =  out$bastaRes$params[,1:paramax],
                              model =  out$bastaRes$modelSpecs[["model"]], Shape =out$bastaRes$modelSpecs[["shape"]],  
                              iseq = floor(seq(0, nrow(out$bastaRes$params), length = ncpus + 1)),
                              xv = xv-MinAge)
  sfStop()
  # Gather estimates:
  for (jj in 1:ncpus) {
    if (jj == 1) {
      Lx <- Lxparal[[jj]]
    } else {
      Lx <- rbind( Lx, Lxparal[[jj]])
    }
  }
  
  # Estilmate key survival metrics from best model--------------------------------
  CVx = apply(Lx,1, CalcCVx, x = xv, dx = rep(dx,length(xv)))
  Hx = apply(Lx,1,CalcHx, dx =dx)
  out$metrics = rbind(out$metrics,
                      tibble::tibble(Data = 'Model',
                             firstage = MinAge,
                             param = rep(c("MLE", "H", "Epx", "G", "CV", "Hx"),each = 4),
                             stat = rep(c("mean", "sd", "lower", "upper"),6),
                             value = c(
                               out$bastaRes$PS$nocov$PS[1,]%>%as.numeric(),
                               out$bastaRes$PS$nocov$PS[2,]%>%as.numeric(),
                               out$bastaRes$PS$nocov$PS[3,]%>%as.numeric(),
                               out$bastaRes$PS$nocov$PS[4,]%>%as.numeric(), 
                               mean(CVx), sd(CVx), quantile(CVx, 0.025), quantile(CVx, 0.975) ,
                               mean(Hx), sd(Hx), quantile(Hx, 0.025), quantile(Hx, 0.975) 
                             )))
  # Remaining life expectancy:
  out$relex_from0<- Sur_relex(Lx, xv = xv, dx = dx)
  # Proba to live 5 year more:
  if(max(xv) >xv[1]+5){
    out$Sur5 <- Sur_age(Lx, xv = xv, Nyear = 5)
  }else{out$Sur5 = "Error : Age max lower than 5 years"} #nocov
  # Proba to live 1 year more:
  out$Sur1 <- Sur_age(Lx, xv = xv, Nyear = 1)
  # Proba to live 1 month more:
  out$Sur1m <- Sur_age(Lx, xv = xv, Nyear = 1/12)
  
  out$metrics = rbind(out$metrics,
                      tibble::tibble(Data = 'Model',
                             firstage = MinAge,
                             param = rep(c("remex0", "L50", "L90", "S1month", "S1year"),each =3),
                             stat = rep(c("mean", "lower", "upper"), 5),
                             value = c(
                               out$relex_from0[1, 2:4]%>%as.numeric(),
                               Sur_xx(Lx, xx = 0.5, xv = xv)%>%as.numeric(),
                               Sur_xx(Lx, xx = 0.1, xv = xv)%>%as.numeric(),
                               out$Sur1m[1, 2:4]%>%as.numeric(),
                               out$Sur1[1, 2:4]%>%as.numeric()
                             )))
  
  # Checks for selected model --------------------------------------------------
  #Check if the life expectancy at max observed age is below MaxLE years old
  MaxAgeobs = max(out$bastaRes$lifeTable$noCov$Mean$Ages)
  idMaxAge = ifelse(max(out$relex_from0$Age) > MaxAgeobs, which(out$relex_from0$Age==MaxAgeobs), length(out$relex_from0$Age))
  out$check$LEmaxOage = out$relex_from0$RemLExp[idMaxAge]

  
  #Check  if the survivorship at mean life expectancy is higher than MinMLE
  lx <-out$bastaRes$lifeTable$noCov$Mean$lx
  dif <-abs(out$bastaRes$lifeTable$noCov$Mean$Ages - out$bastaRes$PS$nocov$PS[1,1])
  out$check$LxatMLE = lx[which(dif == min(dif))]
  out$check$KMMinLx = out$summary$lxMin

  
  
  #Check if kaplan-meier estimator is within the 95% CI of the estimated Lx from the selected model
  roundN = ifelse(max(out$bastaRes$x+MinAge)>5, 2,3)
  Lx = tibble::tibble(Meann = out$bastaRes$surv$nocov[1,],
              Lower = out$bastaRes$surv$nocov[2,],
              Upper = out$bastaRes$surv$nocov[3,],
              Ages = round(out$bastaRes$x+round(MinAge,1),roundN))
  #correct estimates when MinAge >0
  Lx$Meann=Lx$Meann/Lx$Meann[1]
  Lx$Lower=Lx$Lower/Lx$Lower[1]
  Lx$Upper=Lx$Upper/Lx$Upper[1]
  
  LT = out$bastaRes$lifeTable$noCov$ple%>%
    dplyr::mutate(Ages = round(Ages/(5*10^(-roundN)))*(5*10^(-roundN)))%>%
    group_by(Ages)%>%
    summarise(ple = max(ple))%>%
    left_join(Lx)%>%
    tidyr::drop_na(Lower, Upper)%>%
    dplyr::mutate(check = (ple <= Upper & ple >= Lower),
           residual = Meann - ple,
           sign = ifelse(residual <0, -1,1),
           diff = 0)
  LT$diff[2:nrow(LT)] =ifelse(LT$sign[1:(nrow(LT)-1)] == LT$sign[2:nrow(LT)], 0,1)
  LT$diff = cumsum(LT$diff)
  v <- LT%>%
    group_by(diff)%>%
    summarise(resi = abs(sum (residual)))
  check = length(which(LT$check))/nrow(LT)
  out$check$Gof_KM_coeff1 =check
  out$check$Gof_KM_coeff2 =max(v$resi)
 
    #Martingale residuals ---------------------------------------------------------
  #REf = PRice and Jones 2017 bioRxiv A general goodness-of-fit test for survival analysis
  # Censored or dead
  delta = ifelse(out$bastatab$Depart.Type == "D", 1, 0)
  #censoring rate
  rho = length(which(out$bastatab$Depart.Type == "C"))/nrow(out$bastatab)
  # Add age at death and corresponding age id lines for join with Lx
  temp= out$bastatab%>%
    dplyr::mutate(agedeath = (Depart.Date - Birth.Date) / 365.25,
           Ages = round(agedeath/(5*10^(-roundN)))*(5*10^(-roundN)),
           Ages = round(Ages,roundN))
  if (max(temp$Ages)>max(Lx$Ages)) {
    temp = temp%>%
      dplyr::filter(Ages <= max(Lx$Ages))
  }
  temp = temp%>% rowwise()%>%
    dplyr::mutate(idage = which(Lx$Ages==Ages))
  # Martingale residuals
  D = 0.5*(1-(1+delta)* Lx$Meann[temp$idage])
  D = round(D,roundN)
  # Possible value for D
  d = seq(-0.5,0.5,0.01)
  #Observed distribution
  Gobs = cumsum(table(factor(D, levels = d))%>%as.numeric)
  Gobs = Gobs/max(Gobs)
  
  # theoretical probability distribution for martingale residuals
  gi = c((1/2-d[1:50])^(rho/(1-rho)),(1/2-d[51:101])^(rho/(1-rho))+2*rho/(1-rho)*(1-2*d[51:101])^(rho/(1-rho)))
  # theoretical Cumulative distribution
  G=cumsum(gi)/sum(gi)
  out$check$Gof_Martingal_KM = max(abs(Gobs-G))
  out$check$Gof_Martingal_test = out$check$Gof_Martingal_KM<= max(0.13, 1.358/sqrt(nrow(temp)))
  if(!out$check$Gof_Martingal_test){
    out$summary$error = "Gof martingale does not fit" #nocov
    out$summary$Nerr = 10 #nocov
  }
  
  # Plots------------------------------------------------------------------------
  if(!is.null(PlotDir)){
    pdf(file = paste0(PlotDir,"/",out$summary$Nerr,'_', PlotName, "_surcheck.pdf", sep=""),
        width = 6, height = 6)
    plot(out$bastaRes, main = PlotName)
    plot(out$bastaRes, plot.type = 'demorates')
    plot(out$bastaRes, plot.type = 'gof')
    dev.off()
    
    pdf(file = paste0(PlotDir,"/", out$summary$Nerr,'_', PlotName, "_surplot.pdf", sep=""), 
        width = 6, height = 6)
    plot(out$relex_from0$RemLExp~  out$relex_from0$Age, main = PlotName, xlab = "Age (year)", 
         ylab = "Remaining life expectancy", type = "l")
    lines(out$relex_from0$Lower ~  out$relex_from0$Age, lty = 2)
    lines(out$relex_from0$Upper ~  out$relex_from0$Age, lty = 2)
    
    plot(out$Sur1$Sur ~  out$Sur1$Age, 
         xlab = "Age (year)", ylab = 'Age-specific survival', type = "l")
    lines(out$Sur1$Lower ~  out$Sur1$Age, lty = 2)
    lines(out$Sur1$Upper ~  out$Sur1$Age, lty = 2)
    dev.off()
  }
  return(out)
}

