# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Survivorship quantile
#' 
#' Estimate the age at which survivorship reaches a specified level xx
#' 
#' @param Lx \code{numeric} Survivorship
#' @param xv \code{numeric} Age vector
#' @param xx  \code{numeric} Proportion of the population still alive. Between 0 and 1.
#'
#' @return a list including the mean and 95% credible interval age at which xx% of the population is still alive
#' 
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' Lx = matrix(c(seq(1,0,by = -0.1), 1,seq(0.5,0,length.out = 10)),nrow =2)
#' out <- Sur_xx(Lx,  xv = c(0:10), xx = 0.1)
Sur_xx <- function(Lx, xv, xx = 0.5) {
  assert_that(is.numeric(xx))
  assert_that(xx >= 0)
  assert_that(xx <= 1)
  
  Sur_xx_0 <- function(Sx, xx =0.5, xv = seq(0, 50, by = 0.01)){
    return( xv[max(which(Sx>=xx))])}
  
  exMat <- apply(Lx,1, Sur_xx_0, xv = xv , xx=xx)
  
  out <- list(L = mean(exMat), Lower = quantile(exMat,0.025), Upper =  quantile(exMat,0.975))
  
  return(out)
}

