# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Remaining life expectancy
#' 
#' Estimate remaining life expectancy over ages.
#' 
#'
#' @param Lx \code{numeric} Matrix of posterior survivorship trajectories
#' @param dx \code{numeric} Precision for age
#' @param xv \code{numeric} Age vector (same length as Lx)
#'
#' @return a data frame including age, the mean and 95% credible interval of the remaining life expectancy
#' 
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' Lx = matrix(c(seq(1,0,by = -0.1), 1,seq(0.5,0,length.out = 10)),nrow =2)
#' out <- Sur_relex(Lx, dx = 1, xv = c(0:10))
Sur_relex <- function(Lx, dx = 0.01,xv) {
  assert_that(is.numeric(dx))
  assert_that(dx > 0)
  assert_that(is.numeric(Lx))
  Sur_relex_0 <- function( Sx, dx = 0.01) {
    ex <- Sx * 0
    idn0 <- which(Sx > 0.001)
    ex[idn0] <- rev(cumsum(rev(Sx[idn0] * dx))) / Sx[idn0]
    return(ex)
  }
  
  exMat <-apply(Lx,1, Sur_relex_0,  dx = dx)
  exQuants <- data.frame(Age = xv, 
                         RemLExp = apply(exMat, 1,quantile, 0.5), 
                         Lower = apply(exMat, 1, quantile, 0.025),
                         Upper = apply(exMat, 1, quantile, 0.975))
  return(exQuants)
}

