# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Estimate Lx
#' 
#' @param sim \code{numeric} iteration number if the function is run in parallel
#' @param theMat \code{array} The posteriors estimates of the model parameter
#' @param model \code{character}  Name of the basta model: "GO", "EX", "LO" and/or "WE".
#' @param Shape \code{character}  Shape of the basta model: "simple", "Makeham", or "bathtub". 
#' @param iseq \code{numeric}  index boundaries defining the rows processed by each parallel worker
#' @param xv \code{numeric}  Age vector
#'
#' @return Lx
#' 
#' @importFrom paramDemo CalcSurv
#' 
#'
#' @noRd
Sur_Lx <- function(sim= 1, theMat ,model = 'GO', Shape = 'bathtub',  
                   iseq = 1:nrow(theMat), 
                   xv = seq(0, 50, by = 0.01)
) {
  
  idseq <- (iseq[sim] + 1):iseq[sim + 1]
  surage <- t(sapply(idseq, function(ith) {
    theta <- theMat[ith, ]
    Sx <- paramDemo::CalcSurv(theta = theta, x = xv, model = model, shape = Shape)
    return(Sx)
  }))
  return(surage)
}
