# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Kaplan-Meier estimator
#' 
#' Compute the Kaplan-Meier product-limit estimator from individual entry and departure ages.
#' 
#' @param Data \code{data.frame} including at least the following columns *deparAge*, *entryAge* (\code{date}), and *DepartType* 
#'
#' @return A data frame with columns:
#' * Ages: event times
#' * ple: Kaplan-Meier survivorship estimate
#' * event : number of deaths at each age
#' * Snd: Greenwood-type cumulative variance term used downstream
#' 
#' @export
#'
#' @examples
#'
#' entryAge = sample(c(1:10), 200, replace = TRUE)
#' data <- data.frame(
#'   entryAge = entryAge,
#'   deparAge =  entryAge + sample(c(0:10), 200, replace = TRUE),
#'   DepartType = sample(c('C', 'D'), 200, replace = TRUE))
#'
#'
#' out<-Sur_ple(data)
Sur_ple <- function(Data) {
  # Check correct format for inputs --------------------------------------------
  assert_that(is.data.frame(Data))
  assert_that(Data %has_name% c("deparAge", "DepartType", "entryAge"))
  
  # Kaplan-Meier Estimator -----------------------------------------------------
  # Find records with same first and last age:
  Data <- Data%>%
    rowwise()%>%
    dplyr::mutate(idsame = entryAge == deparAge,
           deparAge = ifelse(deparAge < 0.1,0.1, deparAge),
           deparAge = round(ifelse(idsame, deparAge + 1/365.25, deparAge),1))%>%
    arrange(deparAge)
  
  # Number of ages:
  nage <-unique(Data$deparAge)
  
  # Cx and delta:
  Cx <- delx <- Snd <- rep(0, length(nage))
  
  # Fill up Cx and delta:
  ii = 0
  for (agev in nage) {
    ii = ii + 1
    idNx <-Data %>%dplyr::filter(entryAge <= agev,
                          deparAge >= agev)
    delx[ii] <- length(which(Data$DepartType == "D"  & Data$deparAge ==agev))
    Cx[ii] <- 1- delx[ii]/nrow(idNx)
    if(ii==1){
      Snd[ii]=delx[ii]/(nrow(idNx)*(nrow(idNx)-+delx[ii]))
    }else{
      Snd[ii]=Snd[ii-1]+delx[ii]/(nrow(idNx)*(nrow(idNx)-+delx[ii]))
      if((nrow(idNx)*(nrow(idNx)-+delx[ii])) == 0)  Snd[ii]=Snd[ii-1]
    }
  }
  
  # Calculate product limit estimator:
  ple <- cumprod(Cx)
  ple[ple<0]=0
  
  # Add age 0:
  if (nage[1] > 0) {
    nage <- c(0, nage)
    ple <- c(1, ple)
    delx<- c(0, delx)
    Snd<- c(0, Snd)
  }
  
  # Output:
  pleTab <- data.frame(Ages = nage, 
                       ple = ple, event = delx,  
                       Snd = Snd )
  
  return(pleTab)
}

