# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Main survival analysis
#' 
#' Run the survival analysis and calculates key survival metrics
#'
#' @param DataCore \code{data.frame} including at least the following columns *AnimalAnonID*, *BirthDate*, *DepartDate*, *EntryDate*, *MaxBirthDate*, *MinBirthDate*, *EntryType*, *DepartType*, *FirstHoldingInstitution*, *LastHoldingInstitution*, *SexType*, and *BirthType*.
#' @param DeathInformation  \code{data.frame} including at least the following columns *AnimalAnonID* and *RelevantDeathInformationType*.
#' @param BirthType_sel \code{character} The birth type to be selected: Captive, Wild, or All.
#' @param CalculateMetricsFrom \code{vector of characters} indicates which metrics should be calculated from which data: "Raw", "Kaplan-Meier", "Model".
#' @param Models \code{vector of characters} names of the BaSTA Models to run: "GO", "EX", "LO" and/or "WE". see ?basta for more information. 
#' @param Shape \code{character} Shape of the BaSTA model: "simple", "Makeham", "bathtub".  see ?basta for more information.
#' @param MinAge \code{numeric} Ages at which the survival analysis should start in years.  see ?basta for more information.
#' @param MaxAge \code{numeric} Maximum possible age in years. Only used for model predictions. This argument is not used to select data.
#' @param OutlLev1 \code{numeric} Start threshold to select individuals based on the longevity distribution: 100%, 99.9, 99 or 95%. This number must decrease when many errors are expected in longevity data.
#' @param OutlLevmin \code{numeric} Minimum threshold to select individuals based on the longevity distribution: 100%, 99.9, 99 or 95%. 
#' @param UncertDeath \code{numeric}: Maximum uncertainty accepted for death date, in days.
#' @param MinDate \code{character 'YYYY-MM-DD'} Earlier date to include data.
#' @param MinNSur \code{numeric} Minimum number of individual records needed to run the survival analysis.
#' @param MaxNSur \code{numeric} Maximum number of individual records allowed to run the survival analysis.
#' @param MinInstitution \code{numeric} Minimum number of institutions that should hold records to run the survival analysis.
#' @param MinBirthKnown  \code{numeric} between 0 and 1. Minimum proportion of individuals with a known birth month in the data to run the survival analysis.
#' @param MinLx  \code{numeric} Value used for longevity threshold and for checks. between 0 and 1. Minimum reached survivorship from the raw Kaplan-Meier analysis. This number avoids running survival analysis if there are too few dead individuals in the data. Lower is better.
#' @param MinMLE \code{numeric} Value used for checks. Minimum survivorship allowed at mean life expectancy. Between 0 and 1.
#' @param MaxLE \code{numeric} Value used for checks. Maximum remaining life expectancy at last observed age. In years.
#' @param niter  \code{numeric}. Parameter to run the model: number of MCMC iterations. see ?basta for more information.
#' @param burnin  \code{numeric} Parameter to run the model: number of iterations removed so that the model has time to converge. see ?basta for more information.
#' @param thinning  \code{numeric} Parameter to run the model: number of iterations to run before saving a set of parameters. see ?basta for more information.
#' @param nchain  \code{numeric} Parameter to run the model: Number of chains to run.
#' @param ncpus  \code{numeric} Number of computer cores to use. 
#' @param PlotDir \code{character} Directory to save the plots. If NULL, no plot is saved
#' @param PlotName \code{character} Name used to save the plots.
#' @param LastDead  \code{logical} Whether the longest lived individuals should be considered dead.
#' 
#' @return A named list with one element per value of `MinAge`, named
#'   `from<MinAge>` (e.g. `from0`). Each element is itself a list containing
#'   `summary`, `metrics`, `bastaRes`, `DICmods`, `KM_estimator`, `bastatab`,
#'   `relex_from0`, `Sur1`, `Sur5`, `Sur1m`, and `check`. Some components may be
#'   `NULL` depending on `CalculateMetricsFrom` and whether model fitting was successful
#' * a summary of the data used:
#'    * NSelect: Number of individuals selected from filters
#'    * NUncertdeath: Number of individuals selected after filter uncertainty in death
#'    * NBasta: Number of data (individuals) selected for the BaSTA/survival analysis
#'    * Ndead:Number of selected individuals with known age of death used in the BaSTA/survival analysis
#'    * Nrc: Number of selected right-censored individuals
#'    * N8090: Number of selected individuals born between 1980 and 1990
#'    * N9000: Number of selected individuals born between 1990 and 2000
#'    * N0010: Number of selected individuals born between 2000 and 2010
#'    * N1020: Number of selected individuals born between 2010 and 2020
#'    * N2030: Number of selected individuals born between 2020 and 2030
#'    * QBD10: 10% Quantile of birth date distribution among selected individuals
#'    * QBD50: Median of birth date distribution among selected individuals
#'    * QBD90: 90% Quantile of birth date distribution among selected individuals
#'    * BDincert: average uncertainty in birth date: in days among selected individuals
#'    * maxAge: Maximum age of selected known age individuals
#'    * maxAlive:Maximum number of years spent ex situ among selected individuals
#'    * lxMin: Minimum survivorship reached with the raw Kaplan-Meier model
#'    * outLev: threshold selected for the distribution of longevity: 100%, 99.9%, 99% or 95%
#'    * analyzed: logical indicating whether the BaSTA survival model was fitted.
#'    * Nerr, error: error code and message when the model was not fitted or when a goodness-of-fit check failed.
#' * the basta fit of the best model
#' * the DIC table comparing the different fit of the Models
#' * Key survival metrics including Mean life expectancy (MLE & Ex), median life expectancy (L50) and  age at which 90% of the individual died (Longevity = L90) estimated from raw data, the Kaplan-Meier estimator, and the survival model. Estimates include ages from birth or from age at sexual maturity (if given). First year survival, First month survival, Entropy (H and Epx = -log(H)), coefficient of variation (CV) and Gini coefficient (G) are also estimated from the Kaplan-Meier estimator and the survival model.
#' * Checks of the fit for the selected survival model:
#'     * Gof_KM_coeff1: Percentage of age points where the KM estimator is outside of the 95% CI of the survivorship estimated from the survival model.
#'     * Gof_KM_coeff2: Maximum sum of same sign residuals between KM estimator and survival model
#'     * Gof_Martingale: Goodness of fit using Martingale residuals
#'     * LxatMLE: Estimated survivorship at mean life expectancy
#'     * LEmaxOage: Life expectancy at max observed age
#'     * KMMinLx: Minimum survivorship reached by the Kaplan-Meier estimator
#' * The remaining life expectancy per age (relex_from0)
#' * The probability to live 5 years more (Sur5)
#' * Age-specific yearly survival  (Sur1)
#' * Monthly survival  (Sur1m)
#' * If PlotDir is filled, 2 plots are produced: 
#'     * One showing the convergence of chains, together with estimated survivorship and survival and mortality rates.
#'     * The second showing remaining life-expectancy, and the age-specific probabilities to live 5 years and 1 year more.
#'
#' @export
#' @import assertthat tidyverse dplyr
#' 
#' @examples
#' data(toy_core)
#' data(toy_deathinformation)
#' out <- Sur_main(toy_core, DeathInformation = toy_deathinformation, BirthType_sel = "All",
#'                 Models = "GO", Shape = "simple",
#'                 niter = 1000, burnin = 101, thinning = 10, nchain = 3, ncpus = 3)
Sur_main <- function(DataCore,   DeathInformation, 
                     CalculateMetricsFrom = c("Raw", "Kaplan-Meier", "Model"),
                     BirthType_sel = "All",
                     Models = "GO", Shape= "simple",
                     MinAge =0, MaxAge=120, OutlLev1 = NA,OutlLevmin = 95,
                     UncertDeath=365,
                     MinDate = "1980-01-01", MinNSur = 50, MaxNSur = NULL,
                     MinInstitution = 2,
                     MinLx = 0.1, MinBirthKnown = 0.3,
                     MinMLE = 0.1, MaxLE = 2, 
                     LastDead = FALSE,
                     niter = 25000, burnin = 5001, thinning = 20, nchain = 3, 
                     ncpus = 2, PlotDir = NULL, PlotName = '') {
  
  # Check correct format for inputs -----------------------------------------------------------------------
  assert_that(is.data.frame(DataCore))
  assert_that(DataCore  %has_name% c("AnimalAnonID", "BirthDate", "DepartDate",
                                     "EntryDate", "MaxBirthDate", "MinBirthDate",
                                     "EntryType", "DepartType", "FirstHoldingInstitution", 
                                     "LastHoldingInstitution", "SexType", "BirthType"))
  assert_that(is.data.frame(DeathInformation))
  assert_that(DeathInformation %has_name% c("AnimalAnonID","RelevantDeathInformationType"))
 assert_that(is.character(BirthType_sel), length(BirthType_sel) == 1)
  assert_that(BirthType_sel %in% c("Captive", "Wild", "All"))

  assert_that(is.character(Models))
  assert_that(all(Models %in% c("", "GO", "EX", "LO", "WE")))

  assert_that(is.character(CalculateMetricsFrom))
  assert_that(all(CalculateMetricsFrom %in% c("Raw", "Kaplan-Meier", "Model")))

  assert_that(is.character(Shape), length(Shape) == 1)
  assert_that(Shape %in% c("", "simple", "bathtub", "Makeham"))

  assert_that(is.numeric(MinAge), length(MinAge) >= 1)
  assert_that(is.numeric(MaxAge), length(MaxAge) == 1)
  assert_that(all(MinAge < MaxAge))

  if (!is.na(OutlLev1)) {
    assert_that(is.numeric(OutlLev1), length(OutlLev1) == 1)
    assert_that(OutlLev1 <= 100)
  } else {
    OutlLev1 <- 100
  }

  assert_that(is.numeric(OutlLevmin), length(OutlLevmin) == 1)
  assert_that(OutlLevmin <= 100)
  assert_that(OutlLevmin >= 0)

  assert_that(is.numeric(UncertDeath), length(UncertDeath) == 1)
  assert_that(UncertDeath >= 0)

  MinDate <- lubridate::as_date(MinDate)
  assert_that(!is.na(MinDate), msg = "MinDate must be a valid date in format YYYY-MM-DD")

  assert_that(is.numeric(MinNSur), length(MinNSur) == 1)
  if (!is.null(MaxNSur)) assert_that(is.numeric(MaxNSur), length(MaxNSur) == 1)

  assert_that(is.numeric(MinInstitution), length(MinInstitution) == 1, MinInstitution > 0)

  assert_that(is.numeric(MinLx), length(MinLx) == 1)
  assert_that(MinLx >= 0 && MinLx <= 1)

  assert_that(is.numeric(MinMLE), length(MinMLE) == 1)
  assert_that(MinMLE >= 0 && MinMLE <= 1)

  assert_that(is.numeric(MaxLE), length(MaxLE) == 1)

  assert_that(is.numeric(MinBirthKnown), length(MinBirthKnown) == 1)
  assert_that(MinBirthKnown >= 0 && MinBirthKnown <= 1,
              msg = "MinBirthKnown must be a proportion between 0 and 1")

  assert_that(is.logical(LastDead), length(LastDead) == 1)

  assert_that(is.numeric(niter), length(niter) == 1, niter > 0)
  assert_that(is.numeric(burnin), length(burnin) == 1, burnin > 0, burnin < niter)
  assert_that(is.numeric(thinning), length(thinning) == 1, thinning > 0, thinning < niter)
  assert_that(is.numeric(nchain), length(nchain) == 1, nchain > 0)
  assert_that(is.numeric(ncpus), length(ncpus) == 1, ncpus > 0)

  assert_that(is.character(PlotName), length(PlotName) == 1)

  if (!is.null(PlotDir)) {
    checkmate::assert_directory_exists(PlotDir)
  }

  
  # Initialize outputs ---------------------------------------------------------------------------------
  out = list()
  
  # Select individuals with correct birth type----------------------------------------------------------
  if (BirthType_sel != "All"){
    Data<- DataCore %>%
      dplyr::filter(stringr::str_detect(BirthType, pattern = BirthType_sel))
  }else{Data<- DataCore}
  
  # Run Survival Analysis-------------------------------------------------------------------------------
  for(j in seq_along(MinAge)){
     assert_that(MinAge[j] < MaxAge)

    out[[paste0("from",MinAge[j])]]<- Sur_ana(Data, DeathInformation = DeathInformation,
                                              OutlLev1 = OutlLev1, OutlLevmin = OutlLevmin, 
                                              CalculateMetricsFrom = CalculateMetricsFrom,
                                              Models = Models, Shape = Shape,
                                              MinDate = MinDate, UncertDeath = UncertDeath, 
                                              LastDead = LastDead, MinAge = MinAge[j],
                                              MinNSur = MinNSur, MaxNSur = MaxNSur,
                                              MinLx = MinLx,
                                              MinInstitution = MinInstitution,
                                              MinBirthKnown = MinBirthKnown, 
                                              niter = niter, burnin = burnin, thinning = thinning, 
                                              nchain = nchain, ncpus = ncpus) 
    out[[paste0("from",MinAge[j])]] <- append( out[[paste0("from",MinAge[j])]], 
                                               list(relex_from0 = NULL, Sur1 = NULL, Sur5 = NULL, Sur1m = NULL, check = NULL))
    
    #Estimate key survival metrics
    if (out[[paste0("from",MinAge[j])]]$summary$analyzed) {
      out[[paste0("from",MinAge[j])]]  <-Sur_out(out[[paste0("from",MinAge[j])]], 
                                                 MaxAge=MaxAge,ncpus = ncpus, MinAge = MinAge[j],
                                                 PlotDir = PlotDir, PlotName = paste0(PlotName,"_",MinAge[j]),
                                                 MinLx = MinLx, MinMLE = MinMLE, MaxLE = MaxLE
      )
    }
  }
  
  return(out)
}
