# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#' Age-specific survival
#' 
#' Estimate age-specific survival, i.e. the probability of surviving at least Nyear additional years, from the parameters outputs of a Basta model.
#' 
#'
#' @param Lx \code{numeric} Matrix of posterior survivorship trajectories
#' @param xv \code{numeric}  Age vector
#' @param Nyear \code{numeric} number of years to survive Default = 1#
#'
#' @return a data frame including age, the mean and 95% credible interval of the age specific probability to survive \code{Nyear} years.
#' 
#' @export
#' 
#' @importFrom paramDemo CalcSurv
#' @importFrom snowfall sfInit sfLibrary sfClusterApplyLB  sfStop
#' 
#' @examples
#' Lx = matrix(c(seq(1,0,by = -0.1), 1,seq(0.5,0,length.out = 10)),nrow =2)
#' out <- Sur_age(Lx, Nyear = 5, xv = c(0:10))
Sur_age <- function(Lx, xv, Nyear = 1) {
  assert_that(is.numeric(Nyear))
  assert_that(Nyear > 0)
  assert_that(is.numeric(xv))
  assert_that(all(xv >= 0))
  Sur_age_0 <- function(Sx, Nyear = 1, 
                        xv = seq(0, 50, by = 0.01)
  ) {
    
    dep = min(which(xv >= (xv[1]+Nyear)))
    idn0 <- length(Sx)
    ex = Sx[dep:idn0]/Sx[1:(idn0-dep+1)]
    return(ex)
  }
  
  exMat <- apply(Lx, 1, Sur_age_0, Nyear = Nyear,xv = xv )
  exMat[is.nan(exMat)]=0
  exQuants <- tibble::tibble(Age = xv[1:nrow(exMat)] , 
                     Lower = apply(exMat, 1, quantile, 0.025),
                     Upper = apply(exMat, 1, quantile, 0.975))%>%
    dplyr::mutate(Sur = apply(exMat, 1, mean))
  return(exQuants)
}

