# WARNING - Generated by {fusen} from dev/flat_survival.Rmd: do not edit by hand # nolint: line_length_linter.

#'
#' Checks required columns and the logical succession of dates, then formats the
#' data for use in BaSTA.
#'
#' @param coresubset \code{data.frame} including at least the following columns:
#'   *AnimalAnonID*, *binSpecies*, *Class*, *Order*, *Family*, *CommonName*,
#'   *BirthDate*, *DepartDate*, *EntryDate*, *MaxBirthDate*, *MinBirthDate*,
#'   *EntryType*, and *DepartType*.
#' @param DeathInformation \code{data.frame} including at least the following
#'   columns *AnimalAnonID* and *RelevantDeathInformationType*.
#' @param EarliestDate \code{character} Earliest date to include, in
#'   `"YYYY-MM-DD"` format, or \code{NA}.
#' @param LatestDate \code{character} Latest date to include, in `"YYYY-MM-DD"`
#'   format, or \code{NA}.
#' @param OtherCovars \code{character} vector of additional variables to include.
#' @param ExcludeStillBirth \code{logical} Whether stillborn and fetal death
#'   records should be excluded.
#' 
#' @details
#' The function removes:
#' \itemize{
#'   \item individuals with missing values in `BirthDate`, `MinBirthDate`,
#'   `MaxBirthDate`, `EntryDate`, or `DepartDate`;
#'   \item individuals for which the sequence of dates is not logically consistent;
#'   \item stillborn or fetal death records, if requested;
#'   \item individuals with departure date earlier than `EarliestDate`;
#'   \item individuals with entry date later than `LatestDate`.
#' }
#'
#' Departure dates later than `LatestDate` are truncated to `LatestDate`, and the
#' corresponding individuals are treated as right-censored.
#' 
#' @return A \code{data.frame} formatted for BaSTA, with date columns renamed to
#'   `Birth.Date`, `Min.Birth.Date`, `Max.Birth.Date`, `Entry.Date`,
#'   `Depart.Date`, `Entry.Type`, and `Depart.Type`. Additional covariates are
#'   kept if requested.
#'   
#' @export
#' @importFrom tidyr replace_na
#'
#' @examples
#' data(toy_core)
#' data(toy_deathinformation)
#' out<- surv_Bastab(toy_core, DeathInformation = toy_deathinformation,
#'                   EarliestDate = '1990-01-01', LatestDate = '2020-12-31', 
#'                   OtherCovars = "SexType", ExcludeStillBirth = TRUE)
#'
#'
surv_Bastab <- function (coresubset, DeathInformation, 
                         EarliestDate = NA, LatestDate = NA, 
                         OtherCovars = NA, ExcludeStillBirth = FALSE) 
{   
  
   # Check correct format for inputs --------------------------------------------
  inclcols <- c(
    "AnimalAnonID", "binSpecies", "Class", "Order", "Family", "CommonName",
    "BirthDate", "MinBirthDate", "MaxBirthDate", "EntryDate", "DepartDate",
    "EntryType", "DepartType"
  )
  
  assert_that(is.data.frame(coresubset))
  assert_that(coresubset %has_name% inclcols)
  
  assert_that(is.data.frame(DeathInformation))
  assert_that(DeathInformation %has_name% c("AnimalAnonID", "RelevantDeathInformationType"))
  
  assert_that(is.logical(ExcludeStillBirth))
  assert_that(length(ExcludeStillBirth) == 1)
  
  if (all(!is.na(OtherCovars))) {
    assert_that(is.character(OtherCovars))
    assert_that(length(OtherCovars) >= 1)
    assert_that(coresubset %has_name% OtherCovars)
    inclcols <- c(inclcols, OtherCovars)
  }
  
  if (!is.na(EarliestDate)) {
    EarliestDate <- lubridate::as_date(EarliestDate)
    assert_that(!is.na(EarliestDate),
                msg = "EarliestDate must be NA or a valid date in format 'YYYY-MM-DD'")
  }
  
  if (!is.na(LatestDate)) {
    LatestDate <- lubridate::as_date(LatestDate)
    assert_that(!is.na(LatestDate),
                msg = "LatestDate must be NA or a valid date in format 'YYYY-MM-DD'")
  }
  
  if (!is.na(EarliestDate) && !is.na(LatestDate)) {
    assert_that(EarliestDate <= LatestDate,
                msg = "EarliestDate must be earlier than or equal to LatestDate")
  }
  
  # Select columns and join RDI  -----------------------------------------------
  bastadat <- coresubset[, inclcols]%>%
    left_join(DeathInformation%>%select(AnimalAnonID, RelevantDeathInformationType)%>%
                dplyr::filter(RelevantDeathInformationType %in% c("Stillborn","Fetal death")), by = "AnimalAnonID")
  if (all(!is.na(OtherCovars))) {
    colnames(bastadat) <- c("AnimalAnonID", "binSpecies", "Class", 
                            "Order", "Family", "CommonName", "Birth.Date", "Min.Birth.Date", 
                            "Max.Birth.Date", "Entry.Date", "Depart.Date", "Entry.Type", 
                            "Depart.Type",OtherCovars, "RelevantDeathInformationType")
  }else{
    colnames(bastadat) <- c("AnimalAnonID", "binSpecies", "Class", 
                            "Order", "Family", "CommonName", "Birth.Date", "Min.Birth.Date", 
                            "Max.Birth.Date", "Entry.Date", "Depart.Date", "Entry.Type", 
                            "Depart.Type","RelevantDeathInformationType")
    
  }
  
  # Remove individuals with too Early or too late dates, and check logical succession of dates ------------------------
  if (is.na(EarliestDate)) {
    EarliestDate <- min(bastadat$Min.Birth.Date, na.rm = TRUE)
  }else{
    EarliestDate <- lubridate::as_date(EarliestDate)
  }
  if (is.na(LatestDate)) {
    LatestDate <- lubridate::today()
  }else{
    LatestDate <- lubridate::as_date(LatestDate)
  }
  
  bastadat <- bastadat%>%
    dplyr::mutate(Depart.Date = lubridate::as_date(Depart.Date),
           Entry.Date = lubridate::as_date(Entry.Date),
           Min.Birth.Date = lubridate::as_date(Min.Birth.Date),
           Max.Birth.Date = lubridate::as_date(Max.Birth.Date),
           Birth.Date = lubridate::as_date(Birth.Date)
    )%>%
    dplyr::filter(Depart.Date >= EarliestDate,
           Entry.Date <= LatestDate)%>%
    tidyr::drop_na(Birth.Date, Min.Birth.Date, Max.Birth.Date, Entry.Date, Depart.Date)%>%
    dplyr::filter((Min.Birth.Date <= Birth.Date)%>% replace_na(TRUE), 
           (Birth.Date <= Max.Birth.Date)%>% replace_na(TRUE), 
           (Birth.Date <= Entry.Date)%>% replace_na(TRUE), 
           (Entry.Date <= Depart.Date)%>% replace_na(TRUE))%>%
    dplyr::mutate(Depart.Type =dplyr:: if_else (Depart.Date > LatestDate, "C", Depart.Type),
           Depart.Date =dplyr:: if_else (Depart.Date > LatestDate, LatestDate, Depart.Date),
           Entry.Type  =dplyr:: if_else (Entry.Date < EarliestDate, "C", Entry.Type),
           Entry.Date  =dplyr:: if_else (Entry.Date < EarliestDate, EarliestDate, Entry.Date)
    )
  
  # Remove Stillborn if required ------------------------------------------------
  if(ExcludeStillBirth){
    bastadat <- bastadat%>%
      dplyr::filter((Depart.Date != Birth.Date)%>% replace_na(TRUE),
             stringr::str_detect(RelevantDeathInformationType, "Stillborn", negate = T)%>% replace_na(TRUE),
             stringr::str_detect(RelevantDeathInformationType, "Fetal death", negate = T)%>% replace_na(TRUE))
  } 
  
  bastadat <- bastadat%>%
    select(-"RelevantDeathInformationType")
  
  return(bastadat)
}
